# to be used when building in Jenkins
FROM us.gcr.io/platform-205701/alpine:safe-alpine3.12-sec1695-bt699-apm

# Add the capsule JAR and config.yml
COPY accesscontrol-service-capsule.jar keystore.jks config.yml alpn-boot-8.1.13.v20181017.jar protocol.info /opt/harness/

RUN wget https://github.com/mikefarah/yq/releases/download/3.3.2/yq_linux_amd64 -O /usr/bin/yq -O /usr/bin/yq
RUN chmod +x /usr/bin/yq

COPY scripts /opt/harness

RUN chmod +x /opt/harness/*.sh
RUN mkdir /opt/harness/plugins

WORKDIR /opt/harness

CMD [ "./run.sh" ]