"""
Generated by command:
bq show --format=prettyjson ce-prod-274307:BillingReport_whejvm7ntje2fz99pdo2ya.preAggregated | jq
"""

preAggreagtedTableSchema = [
      {
        "name": "cost",
        "type": "FLOAT"
      },
      {
        "name": "gcpProduct",
        "type": "STRING"
      },
      {
        "name": "gcpSkuId",
        "type": "STRING"
      },
      {
        "name": "gcpSkuDescription",
        "type": "STRING"
      },
      {
        "name": "startTime",
        "type": "TIMESTAMP"
      },
      {
        "name": "gcpProjectId",
        "type": "STRING"
      },
      {
        "name": "region",
        "type": "STRING"
      },
      {
        "name": "zone",
        "type": "STRING"
      },
      {
        "name": "gcpBillingAccountId",
        "type": "STRING"
      },
      {
        "name": "cloudProvider",
        "type": "STRING"
      },
      {
        "name": "awsBlendedRate",
        "type": "STRING"
      },
      {
        "name": "awsBlendedCost",
        "type": "FLOAT"
      },
      {
        "name": "awsUnblendedRate",
        "type": "STRING"
      },
      {
        "name": "awsUnblendedCost",
        "type": "FLOAT"
      },
      {
        "name": "awsServicecode",
        "type": "STRING"
      },
      {
        "name": "awsAvailabilityzone",
        "type": "STRING"
      },
      {
        "name": "awsUsageaccountid",
        "type": "STRING"
      },
      {
        "name": "awsInstancetype",
        "type": "STRING"
      },
      {
        "name": "awsUsagetype",
        "type": "STRING"
      }
    ]