package io.harness.event.reconciliation.deployment;

public enum ReconcilationAction {
  NONE,
  ADD_MISSING_RECORDS,
  DUPLICATE_REMOVAL,
  STATUS_RECONCILIATION,
  DUPLICATE_REMOVAL_ADD_MISSING_RECORDS,
  DUPLICATE_REMOVAL_STATUS_RECONCILIATION,
  ADD_MISSING_RECORDS_STATUS_RECONCILIATION,
  DUPLICATE_REMOVAL_ADD_MISSING_RECORDS_STATUS_RECONCILIATION
}
