# UBI BASE IMAGE + JDK

# Usage: Application runtime base image for java based application, CIE agent base image
# Test image locally by running this command:
#
# $ docker build \
#     -f Dockerfile-ubi-java-base" \
#     -t <tag> \
#     .

FROM us.gcr.io/platform-205701/ubi/ubi-base:latest
RUN curl -OL https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.15%2B10/OpenJDK11U-jdk_x64_linux_hotspot_11.0.15_10.tar.gz \
 && mkdir -p /opt/harness/OpenJDK11 && tar -xzf OpenJDK11U-jdk_x64_linux_hotspot_11.0.15_10.tar.gz -C /opt/harness/OpenJDK11 && ls -al /opt/harness/OpenJDK11/jdk-11.0.15+10 \
 && /opt/harness/OpenJDK11/jdk-11.0.15+10/bin/java -version

ENV JAVA_HOME=/opt/harness/OpenJDK11/jdk-11.0.15+10
ENV PATH=$JAVA_HOME/bin:$PATH