# BASE IMAGE - UBI

# Usage: Absolute base image for all images. Father of all!!
# Test image locally by running this command:
#
# $ docker build \
#     -f Dockerfile-ubi-base" \
#     -t <tag> \
#     .

FROM registry.access.redhat.com/ubi8/ubi:8.6-754
CMD ["/bin/sh"]
RUN yum -y update && yum -y install curl libstdc++.i686 make bash

#Installing yq
RUN curl -L https://github.com/mikefarah/yq/releases/download/v4.25.1/yq_linux_amd64 -o /usr/bin/yq && chmod +x /usr/bin/yq

RUN set -x \
    && mkdir -p /opt/harness/plugins \
    && chown -R 65534:65534 /opt/harness \
    && chmod -R 700 /opt/harness

WORKDIR /opt/harness

USER 65534