# to be used when building in Jenkins
FROM harness/serverjre_8:242

# Add the capsule JAR and config.yml
COPY ng-manager-capsule.jar keystore.jks config.yml /opt/harness/

COPY scripts /opt/harness

RUN chmod +x /opt/harness/*.sh
RUN mkdir /opt/harness/plugins

WORKDIR /opt/harness

CMD [ "./run.sh" ]