/*
 * Copyright 2022 Harness Inc. All rights reserved.
 * Use of this source code is governed by the PolyForm Shield 1.0.0 license
 * that can be found in the licenses directory at the root of this repository, also available at
 * https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.
 */

package io.harness.serializer.morphia;

import static io.harness.annotations.dev.HarnessTeam.PL;

import io.harness.annotations.dev.OwnedBy;
import io.harness.ccm.cluster.entities.AzureKubernetesCluster;
import io.harness.ccm.cluster.entities.ClusterRecord;
import io.harness.ccm.cluster.entities.DirectKubernetesCluster;
import io.harness.ccm.cluster.entities.EcsCluster;
import io.harness.ccm.cluster.entities.GcpKubernetesCluster;
import io.harness.ccm.cluster.entities.PricingProfile;
import io.harness.ccm.communication.entities.CECommunications;
import io.harness.ccm.communication.entities.CESlackWebhook;
import io.harness.ccm.config.GcpBillingAccount;
import io.harness.ccm.config.GcpOrganization;
import io.harness.ccm.config.GcpServiceAccount;
import io.harness.dashboard.DashboardSettings;
import io.harness.event.MigratedAccountTracker;
import io.harness.event.reconciliation.deployment.DeploymentReconRecord;
import io.harness.event.reconciliation.looker.LookerEntityReconRecord;
import io.harness.execution.export.request.ExportExecutionsRequest;
import io.harness.governance.pipeline.service.model.PipelineGovernanceConfig;
import io.harness.marketplace.gcp.procurement.pubsub.ProcurementPubsubMessage;
import io.harness.mongo.index.migrator.AggregateResult;
import io.harness.morphia.MorphiaRegistrar;
import io.harness.morphia.MorphiaRegistrarHelperPut;

import software.wings.api.ARMStateExecutionData;
import software.wings.api.AmiStepExecutionSummary;
import software.wings.api.ApprovalStateExecutionData;
import software.wings.api.ArtifactCollectionExecutionData;
import software.wings.api.AwsAmiDeployStateExecutionData;
import software.wings.api.AwsAmiSetupExecutionData;
import software.wings.api.AwsAmiSwitchRoutesStateExecutionData;
import software.wings.api.AwsAutoScalingGroupDeploymentInfo;
import software.wings.api.AwsCodeDeployDeploymentInfo;
import software.wings.api.AzureVMSSDeploymentInfo;
import software.wings.api.AzureWebAppDeploymentInfo;
import software.wings.api.BarrierExecutionData;
import software.wings.api.BarrierStepExecutionSummary;
import software.wings.api.CommandStateExecutionData;
import software.wings.api.CommandStepExecutionSummary;
import software.wings.api.ContainerDeploymentInfoWithLabels;
import software.wings.api.ContainerDeploymentInfoWithNames;
import software.wings.api.CustomDeploymentTypeInfo;
import software.wings.api.DeploymentEvent;
import software.wings.api.DeploymentStepTimeSeriesEvent;
import software.wings.api.DeploymentSummary;
import software.wings.api.DeploymentTimeSeriesEvent;
import software.wings.api.EcsStepExecutionSummary;
import software.wings.api.ElbStateExecutionData;
import software.wings.api.EmailStateExecutionData;
import software.wings.api.EnvStateExecutionData;
import software.wings.api.ExecutionInterruptTimeSeriesEvent;
import software.wings.api.HelmDeployStateExecutionData;
import software.wings.api.HelmSetupExecutionSummary;
import software.wings.api.HttpStateExecutionData;
import software.wings.api.InstanceChangeEvent;
import software.wings.api.InstanceEvent;
import software.wings.api.InstanceFetchStateExecutionSummary;
import software.wings.api.JenkinsExecutionData;
import software.wings.api.K8sDeploymentInfo;
import software.wings.api.KubernetesSteadyStateCheckExecutionData;
import software.wings.api.KubernetesSteadyStateCheckExecutionSummary;
import software.wings.api.KubernetesSwapServiceSelectorsExecutionData;
import software.wings.api.PcfDeploymentInfo;
import software.wings.api.PhaseExecutionData;
import software.wings.api.PhaseStepExecutionData;
import software.wings.api.ResourceConstraintExecutionData;
import software.wings.api.ResourceConstraintStepExecutionSummary;
import software.wings.api.SelectNodeStepExecutionSummary;
import software.wings.api.SelectedNodeExecutionData;
import software.wings.api.SkipStateExecutionData;
import software.wings.api.SpotinstAmiDeploymentInfo;
import software.wings.api.TerraformApplyMarkerParam;
import software.wings.api.arm.ARMOutputVariables;
import software.wings.api.artifact.ServiceArtifactElements;
import software.wings.api.artifact.ServiceArtifactVariableElements;
import software.wings.api.customdeployment.InstanceFetchStateExecutionData;
import software.wings.api.ecs.EcsListenerUpdateExecutionSummary;
import software.wings.api.ecs.EcsListenerUpdateStateExecutionData;
import software.wings.api.ecs.EcsRoute53WeightUpdateStateExecutionData;
import software.wings.api.helm.ServiceHelmElements;
import software.wings.api.instancedetails.InstanceInfoVariables;
import software.wings.api.k8s.K8sApplicationManifestSourceInfo;
import software.wings.api.k8s.K8sCanaryDeleteServiceElement;
import software.wings.api.k8s.K8sExecutionSummary;
import software.wings.api.k8s.K8sGitConfigMapInfo;
import software.wings.api.k8s.K8sGitFetchInfo;
import software.wings.api.k8s.K8sGitInfo;
import software.wings.api.k8s.K8sHelmDeploymentElement;
import software.wings.api.k8s.K8sStateExecutionData;
import software.wings.api.lambda.AwsLambdaDeploymentInfo;
import software.wings.api.pcf.DeploySweepingOutputPcf;
import software.wings.api.pcf.InfoVariables;
import software.wings.api.pcf.PcfDeployExecutionSummary;
import software.wings.api.pcf.PcfDeployStateExecutionData;
import software.wings.api.pcf.PcfPluginExecutionSummary;
import software.wings.api.pcf.PcfPluginStateExecutionData;
import software.wings.api.pcf.PcfRouteSwapExecutionSummary;
import software.wings.api.pcf.PcfRouteUpdateStateExecutionData;
import software.wings.api.pcf.PcfSetupExecutionSummary;
import software.wings.api.pcf.PcfSetupStateExecutionData;
import software.wings.api.pcf.SetupSweepingOutputPcf;
import software.wings.api.pcf.SwapRouteRollbackSweepingOutputPcf;
import software.wings.api.terraform.TerraformOutputVariables;
import software.wings.api.terragrunt.TerragruntApplyMarkerParam;
import software.wings.api.terragrunt.TerragruntOutputVariables;
import software.wings.audit.AuditHeader;
import software.wings.audit.AuditRecord;
import software.wings.audit.EntityAuditRecord;
import software.wings.beans.ARMInfrastructureProvisioner;
import software.wings.beans.Account;
import software.wings.beans.ActionableNotification;
import software.wings.beans.Activity;
import software.wings.beans.ApiKeyEntry;
import software.wings.beans.Application;
import software.wings.beans.ApprovalNotification;
import software.wings.beans.AuditPreference;
import software.wings.beans.AuthToken;
import software.wings.beans.AwsAmiInfrastructureMapping;
import software.wings.beans.AwsInfrastructureMapping;
import software.wings.beans.AwsLambdaInfraStructureMapping;
import software.wings.beans.AzureInfrastructureMapping;
import software.wings.beans.AzureKubernetesInfrastructureMapping;
import software.wings.beans.AzureVMSSInfrastructureMapping;
import software.wings.beans.AzureWebAppInfrastructureMapping;
import software.wings.beans.BarrierInstance;
import software.wings.beans.Base;
import software.wings.beans.BasicOrchestrationWorkflow;
import software.wings.beans.BlueGreenOrchestrationWorkflow;
import software.wings.beans.BuildWorkflow;
import software.wings.beans.CanaryOrchestrationWorkflow;
import software.wings.beans.CanaryWorkflowExecutionAdvisor;
import software.wings.beans.CloudFormationInfrastructureProvisioner;
import software.wings.beans.CodeDeployInfrastructureMapping;
import software.wings.beans.ConfigFile;
import software.wings.beans.ContainerInfrastructureMapping;
import software.wings.beans.CustomInfrastructureMapping;
import software.wings.beans.DelegateSequenceConfig;
import software.wings.beans.DeletedEntity;
import software.wings.beans.DeploymentPreference;
import software.wings.beans.DeploymentSpecification;
import software.wings.beans.DirectKubernetesInfrastructureMapping;
import software.wings.beans.EcsBlueGreenOrchestrationWorkflow;
import software.wings.beans.EcsInfrastructureMapping;
import software.wings.beans.EmailVerificationToken;
import software.wings.beans.EntityVersion;
import software.wings.beans.EntityVersionCollection;
import software.wings.beans.EntityYamlRecord;
import software.wings.beans.Environment;
import software.wings.beans.ExportExecutionsNotification;
import software.wings.beans.ExternalServiceAuthToken;
import software.wings.beans.FailureNotification;
import software.wings.beans.GcpKubernetesInfrastructureMapping;
import software.wings.beans.GcsFileMetadata;
import software.wings.beans.GitCommit;
import software.wings.beans.GitFileActivitySummary;
import software.wings.beans.HarnessTag;
import software.wings.beans.HarnessTagLink;
import software.wings.beans.Idempotent;
import software.wings.beans.InformationNotification;
import software.wings.beans.InfrastructureMapping;
import software.wings.beans.InfrastructureProvisioner;
import software.wings.beans.LambdaSpecification;
import software.wings.beans.License;
import software.wings.beans.Log;
import software.wings.beans.ManagerConfiguration;
import software.wings.beans.MarketPlace;
import software.wings.beans.MultiServiceOrchestrationWorkflow;
import software.wings.beans.Notification;
import software.wings.beans.NotificationBatch;
import software.wings.beans.NotificationGroup;
import software.wings.beans.NotificationReceiverInfo;
import software.wings.beans.PcfInfrastructureMapping;
import software.wings.beans.Permit;
import software.wings.beans.PhysicalInfrastructureMapping;
import software.wings.beans.PhysicalInfrastructureMappingBase;
import software.wings.beans.PhysicalInfrastructureMappingWinRm;
import software.wings.beans.Pipeline;
import software.wings.beans.PipelineExecution;
import software.wings.beans.Preference;
import software.wings.beans.RancherKubernetesInfrastructureMapping;
import software.wings.beans.ResourceConstraintInstance;
import software.wings.beans.ResourceConstraintNotification;
import software.wings.beans.ResourceLookup;
import software.wings.beans.Role;
import software.wings.beans.RollingOrchestrationWorkflow;
import software.wings.beans.RuntimeInputsConfig;
import software.wings.beans.Schema;
import software.wings.beans.Service;
import software.wings.beans.ServiceInstance;
import software.wings.beans.ServiceTemplate;
import software.wings.beans.SettingAttribute;
import software.wings.beans.SystemCatalog;
import software.wings.beans.TerraformInfrastructureProvisioner;
import software.wings.beans.TerragruntInfrastructureProvisioner;
import software.wings.beans.User;
import software.wings.beans.UserInvite;
import software.wings.beans.Workflow;
import software.wings.beans.WorkflowExecution;
import software.wings.beans.alert.Alert;
import software.wings.beans.alert.AlertNotificationRule;
import software.wings.beans.alert.ApprovalNeededAlert;
import software.wings.beans.alert.ArtifactCollectionFailedAlert;
import software.wings.beans.alert.DelegatesDownAlert;
import software.wings.beans.alert.DeploymentFreezeEventAlert;
import software.wings.beans.alert.DeploymentRateApproachingLimitAlert;
import software.wings.beans.alert.EmailSendingFailedAlert;
import software.wings.beans.alert.GitConnectionErrorAlert;
import software.wings.beans.alert.GitSyncErrorAlert;
import software.wings.beans.alert.InstanceUsageLimitAlert;
import software.wings.beans.alert.InvalidSMTPConfigAlert;
import software.wings.beans.alert.KmsSetupAlert;
import software.wings.beans.alert.ManifestCollectionFailedAlert;
import software.wings.beans.alert.ManualInterventionNeededAlert;
import software.wings.beans.alert.NotificationRulesStatus;
import software.wings.beans.alert.ResourceUsageApproachingLimitAlert;
import software.wings.beans.alert.SSOSyncFailedAlert;
import software.wings.beans.alert.SettingAttributeValidationFailedAlert;
import software.wings.beans.alert.UsageLimitExceededAlert;
import software.wings.beans.alert.cv.ContinuousVerificationAlertData;
import software.wings.beans.alert.cv.ContinuousVerificationDataCollectionAlert;
import software.wings.beans.appmanifest.ApplicationManifest;
import software.wings.beans.appmanifest.HelmChart;
import software.wings.beans.appmanifest.ManifestFile;
import software.wings.beans.approval.ApprovalPollingJobEntity;
import software.wings.beans.artifact.AcrArtifactStream;
import software.wings.beans.artifact.AmazonS3ArtifactStream;
import software.wings.beans.artifact.AmiArtifactStream;
import software.wings.beans.artifact.ArtifactStream;
import software.wings.beans.artifact.ArtifactView;
import software.wings.beans.artifact.ArtifactoryArtifactStream;
import software.wings.beans.artifact.AzureArtifactsArtifactStream;
import software.wings.beans.artifact.AzureMachineImageArtifactStream;
import software.wings.beans.artifact.BambooArtifactStream;
import software.wings.beans.artifact.CustomArtifactStream;
import software.wings.beans.artifact.DockerArtifactStream;
import software.wings.beans.artifact.EcrArtifactStream;
import software.wings.beans.artifact.GcrArtifactStream;
import software.wings.beans.artifact.GcsArtifactStream;
import software.wings.beans.artifact.JenkinsArtifactStream;
import software.wings.beans.artifact.NexusArtifactStream;
import software.wings.beans.artifact.SftpArtifactStream;
import software.wings.beans.artifact.SmbArtifactStream;
import software.wings.beans.baseline.WorkflowExecutionBaseline;
import software.wings.beans.ce.depricated.CECloudAccountOld;
import software.wings.beans.ce.depricated.GcpServiceAccountOld;
import software.wings.beans.command.Command;
import software.wings.beans.command.ServiceCommand;
import software.wings.beans.commandlibrary.CommandEntity;
import software.wings.beans.commandlibrary.CommandVersionEntity;
import software.wings.beans.container.ContainerTask;
import software.wings.beans.container.EcsContainerTask;
import software.wings.beans.container.EcsServiceSpecification;
import software.wings.beans.container.HelmChartSpecification;
import software.wings.beans.container.KubernetesContainerTask;
import software.wings.beans.container.PcfServiceSpecification;
import software.wings.beans.container.UserDataSpecification;
import software.wings.beans.datatretention.LongerDataRetentionState;
import software.wings.beans.entityinterface.TagAware;
import software.wings.beans.governance.GovernanceConfig;
import software.wings.beans.infrastructure.CloudFormationRollbackConfig;
import software.wings.beans.infrastructure.TerraformConfig;
import software.wings.beans.infrastructure.instance.ContainerDeploymentInfo;
import software.wings.beans.infrastructure.instance.Instance;
import software.wings.beans.infrastructure.instance.ManualSyncJob;
import software.wings.beans.infrastructure.instance.ServerlessInstance;
import software.wings.beans.infrastructure.instance.SyncStatus;
import software.wings.beans.infrastructure.instance.TerragruntConfig;
import software.wings.beans.infrastructure.instance.info.AutoScalingGroupInstanceInfo;
import software.wings.beans.infrastructure.instance.info.AwsLambdaInstanceInfo;
import software.wings.beans.infrastructure.instance.info.AzureVMSSInstanceInfo;
import software.wings.beans.infrastructure.instance.info.AzureWebAppInstanceInfo;
import software.wings.beans.infrastructure.instance.info.CodeDeployInstanceInfo;
import software.wings.beans.infrastructure.instance.info.Ec2InstanceInfo;
import software.wings.beans.infrastructure.instance.info.PcfInstanceInfo;
import software.wings.beans.infrastructure.instance.info.PhysicalHostInstanceInfo;
import software.wings.beans.infrastructure.instance.info.SpotinstAmiInstanceInfo;
import software.wings.beans.infrastructure.instance.stats.InstanceStatsSnapshot;
import software.wings.beans.infrastructure.instance.stats.ServerlessInstanceStats;
import software.wings.beans.loginSettings.LoginSettings;
import software.wings.beans.marketplace.gcp.GCPBillingJobEntity;
import software.wings.beans.marketplace.gcp.GCPMarketplaceCustomer;
import software.wings.beans.marketplace.gcp.GCPUsageReport;
import software.wings.beans.peronalization.Personalization;
import software.wings.beans.security.AccessRequest;
import software.wings.beans.security.HarnessUserGroup;
import software.wings.beans.security.UserGroup;
import software.wings.beans.security.access.Whitelist;
import software.wings.beans.shellscript.provisioner.ShellScriptInfrastructureProvisioner;
import software.wings.beans.sso.LdapSettings;
import software.wings.beans.sso.OauthSettings;
import software.wings.beans.sso.SSOSettings;
import software.wings.beans.sso.SamlSettings;
import software.wings.beans.template.CopiedTemplateMetadata;
import software.wings.beans.template.ImportedTemplate;
import software.wings.beans.template.ImportedTemplateMetadata;
import software.wings.beans.template.Template;
import software.wings.beans.template.TemplateFolder;
import software.wings.beans.template.TemplateGallery;
import software.wings.beans.template.TemplateVersion;
import software.wings.beans.template.VersionedTemplate;
import software.wings.beans.template.artifactsource.ArtifactSourceTemplate;
import software.wings.beans.template.artifactsource.CustomArtifactSourceTemplate;
import software.wings.beans.template.command.HttpTemplate;
import software.wings.beans.template.command.PcfCommandTemplate;
import software.wings.beans.template.command.ShellScriptTemplate;
import software.wings.beans.template.command.SshCommandTemplate;
import software.wings.beans.trigger.ArtifactTriggerCondition;
import software.wings.beans.trigger.NewInstanceTriggerCondition;
import software.wings.beans.trigger.PipelineTriggerCondition;
import software.wings.beans.trigger.ScheduledTriggerCondition;
import software.wings.beans.trigger.Trigger;
import software.wings.beans.trigger.TriggerExecution;
import software.wings.beans.trigger.WebHookTriggerCondition;
import software.wings.beans.trigger.WorkflowAction;
import software.wings.beans.yaml.GitSuccessFulChangeDetail;
import software.wings.beans.yaml.HarnessSuccessFulChangeDetail;
import software.wings.beans.yaml.YamlSuccessfulChange;
import software.wings.collect.ArtifactCollectionCallback;
import software.wings.collect.CollectEvent;
import software.wings.delegatetasks.buildsource.BuildSourceCallback;
import software.wings.delegatetasks.buildsource.BuildSourceCleanupCallback;
import software.wings.helpers.ext.cloudformation.CloudFormationCompletionFlag;
import software.wings.infra.AwsAmiInfrastructure;
import software.wings.infra.AwsEcsInfrastructure;
import software.wings.infra.AwsInstanceInfrastructure;
import software.wings.infra.AwsLambdaInfrastructure;
import software.wings.infra.AzureInstanceInfrastructure;
import software.wings.infra.AzureKubernetesService;
import software.wings.infra.AzureVMSSInfra;
import software.wings.infra.AzureWebAppInfra;
import software.wings.infra.CodeDeployInfrastructure;
import software.wings.infra.CustomInfrastructure;
import software.wings.infra.DirectKubernetesInfrastructure;
import software.wings.infra.GoogleKubernetesEngine;
import software.wings.infra.InfrastructureDefinition;
import software.wings.infra.PcfInfraStructure;
import software.wings.infra.PhysicalInfra;
import software.wings.infra.PhysicalInfraWinrm;
import software.wings.instancesyncv2.model.InstanceSyncTaskDetails;
import software.wings.metrics.TimeSeriesDataRecord;
import software.wings.persistence.AppContainer;
import software.wings.persistence.BaseFile;
import software.wings.persistence.artifact.Artifact;
import software.wings.persistence.artifact.ArtifactFile;
import software.wings.persistence.mail.EmailData;
import software.wings.prune.PruneEvent;
import software.wings.resources.DelegateFileResource.FileIdempotentResult;
import software.wings.scheduler.events.segment.SegmentGroupEventJobContext;
import software.wings.search.framework.ElasticsearchBulkMigrationJob;
import software.wings.search.framework.SearchDistributedLock;
import software.wings.search.framework.SearchEntityIndexState;
import software.wings.search.framework.SearchSourceEntitySyncState;
import software.wings.service.impl.ExecutionEvent;
import software.wings.service.impl.ThirdPartyApiCallLog;
import software.wings.service.impl.WorkflowExecutionUpdate;
import software.wings.service.impl.analysis.AnalysisContext;
import software.wings.service.impl.analysis.CVFeedbackRecord;
import software.wings.service.impl.analysis.ContinuousVerificationExecutionMetaData;
import software.wings.service.impl.analysis.DataCollectionCallback;
import software.wings.service.impl.analysis.ExperimentalLogMLAnalysisRecord;
import software.wings.service.impl.analysis.ExperimentalMessageComparisonResult;
import software.wings.service.impl.analysis.ExperimentalMetricAnalysisRecord;
import software.wings.service.impl.analysis.LabeledLogRecord;
import software.wings.service.impl.analysis.LogDataRecord;
import software.wings.service.impl.analysis.LogMLAnalysisRecord;
import software.wings.service.impl.analysis.LogMLFeedbackRecord;
import software.wings.service.impl.analysis.MetricAnalysisRecord;
import software.wings.service.impl.analysis.SupervisedTSThreshold;
import software.wings.service.impl.analysis.SupervisedTrainingStatus;
import software.wings.service.impl.analysis.TimeSeriesKeyTransactions;
import software.wings.service.impl.analysis.TimeSeriesMLAnalysisRecord;
import software.wings.service.impl.analysis.TimeSeriesMLScores;
import software.wings.service.impl.analysis.TimeSeriesMLTransactionThresholds;
import software.wings.service.impl.analysis.TimeSeriesMetricGroup;
import software.wings.service.impl.analysis.TimeSeriesMetricTemplates;
import software.wings.service.impl.analysis.TimeSeriesRawData;
import software.wings.service.impl.analysis.TimeSeriesRiskSummary;
import software.wings.service.impl.email.EmailNotificationCallBack;
import software.wings.service.impl.event.AccountEntityEvent;
import software.wings.service.impl.event.AlertEvent;
import software.wings.service.impl.event.timeseries.TimeSeriesBatchEventInfo;
import software.wings.service.impl.event.timeseries.TimeSeriesEventInfo;
import software.wings.service.impl.instance.InstanceSyncPerpetualTaskInfo;
import software.wings.service.impl.instance.backup.InstanceSyncPTInfoBackup;
import software.wings.service.impl.newrelic.LearningEngineAnalysisTask;
import software.wings.service.impl.newrelic.LearningEngineExperimentalAnalysisTask;
import software.wings.service.impl.newrelic.MLExperiments;
import software.wings.service.impl.newrelic.NewRelicMarkerExecutionData;
import software.wings.service.impl.newrelic.NewRelicMetricAnalysisRecord;
import software.wings.service.impl.newrelic.NewRelicMetricDataRecord;
import software.wings.service.impl.splunk.SplunkAnalysisCluster;
import software.wings.service.impl.trigger.TriggerCallback;
import software.wings.service.impl.trigger.TriggerServiceImpl.TriggerIdempotentResult;
import software.wings.service.impl.yaml.GitCommandCallback;
import software.wings.service.impl.yaml.gitdiff.gitaudit.AuditYamlHelperForFailedChanges.ArtifactStreamWithOnlyAuditNeededData;
import software.wings.service.impl.yaml.gitdiff.gitaudit.AuditYamlHelperForFailedChanges.InfraMappingWithOnlyAuditNeededData;
import software.wings.service.impl.yaml.gitdiff.gitaudit.AuditYamlHelperForFailedChanges.ProvisionerWithOnlyAuditNeededData;
import software.wings.sm.AwsLambdaVerification;
import software.wings.sm.ElementNotifyResponseData;
import software.wings.sm.ExecutionInterrupt;
import software.wings.sm.ExecutionResumeAllCallback;
import software.wings.sm.ExecutionStatusData;
import software.wings.sm.ExecutionWaitCallback;
import software.wings.sm.ExecutionWaitRetryCallback;
import software.wings.sm.PhaseExecutionSummary;
import software.wings.sm.PhaseStepExecutionSummary;
import software.wings.sm.PipelineContinueWithInputsCallback;
import software.wings.sm.ResourceConstraintStatusData;
import software.wings.sm.StateExecutionInstance;
import software.wings.sm.StateMachine;
import software.wings.sm.StateMachineResumeCallback;
import software.wings.sm.states.APMVerificationState;
import software.wings.sm.states.AppDynamicsState;
import software.wings.sm.states.ApprovalResumeState;
import software.wings.sm.states.ApprovalState;
import software.wings.sm.states.ArtifactCheckState;
import software.wings.sm.states.ArtifactCollectLoopState;
import software.wings.sm.states.ArtifactCollectionState;
import software.wings.sm.states.AwsAmiRollbackSwitchRoutesState;
import software.wings.sm.states.AwsAmiRollbackTrafficShiftAlbSwitchRoutesState;
import software.wings.sm.states.AwsAmiServiceDeployState;
import software.wings.sm.states.AwsAmiServiceRollback;
import software.wings.sm.states.AwsAmiServiceSetup;
import software.wings.sm.states.AwsAmiServiceTrafficShiftAlbDeployState;
import software.wings.sm.states.AwsAmiServiceTrafficShiftAlbSetup;
import software.wings.sm.states.AwsAmiSwitchRoutesState;
import software.wings.sm.states.AwsAmiTrafficShiftAlbSwitchRoutesState;
import software.wings.sm.states.AwsCodeDeployRollback;
import software.wings.sm.states.AwsCodeDeployState;
import software.wings.sm.states.AwsLambdaRollback;
import software.wings.sm.states.AwsLambdaState;
import software.wings.sm.states.AwsNodeSelectState;
import software.wings.sm.states.AzureNodeSelectState;
import software.wings.sm.states.BambooState;
import software.wings.sm.states.BarrierState;
import software.wings.sm.states.BugsnagState;
import software.wings.sm.states.CVNGState;
import software.wings.sm.states.CloudWatchState;
import software.wings.sm.states.CollectRemainingInstancesState;
import software.wings.sm.states.CommandState;
import software.wings.sm.states.CustomLogVerificationState;
import software.wings.sm.states.DatadogLogState;
import software.wings.sm.states.DatadogState;
import software.wings.sm.states.DcNodeSelectState;
import software.wings.sm.states.DynatraceState;
import software.wings.sm.states.EcsBGRollbackRoute53DNSWeightState;
import software.wings.sm.states.EcsBGUpdateListnerRollbackState;
import software.wings.sm.states.EcsBGUpdateListnerState;
import software.wings.sm.states.EcsBGUpdateRoute53DNSWeightState;
import software.wings.sm.states.EcsBlueGreenServiceSetup;
import software.wings.sm.states.EcsBlueGreenServiceSetupRoute53DNS;
import software.wings.sm.states.EcsDaemonServiceSetup;
import software.wings.sm.states.EcsRunTaskDeploy;
import software.wings.sm.states.EcsServiceDeploy;
import software.wings.sm.states.EcsServiceRollback;
import software.wings.sm.states.EcsServiceSetup;
import software.wings.sm.states.EcsSetupRollback;
import software.wings.sm.states.EcsSteadyStateCheck;
import software.wings.sm.states.ElasticLoadBalancerState;
import software.wings.sm.states.ElkAnalysisState;
import software.wings.sm.states.EmailState;
import software.wings.sm.states.EnvLoopResumeState;
import software.wings.sm.states.EnvLoopState;
import software.wings.sm.states.EnvResumeState;
import software.wings.sm.states.EnvState;
import software.wings.sm.states.EnvState.EnvExecutionResponseData;
import software.wings.sm.states.ForkState;
import software.wings.sm.states.ForkState.ForkStateExecutionData;
import software.wings.sm.states.GcbState;
import software.wings.sm.states.GcpClusterSetup;
import software.wings.sm.states.HelmDeployState;
import software.wings.sm.states.HelmRollbackState;
import software.wings.sm.states.HttpState;
import software.wings.sm.states.InstanaState;
import software.wings.sm.states.JenkinsState;
import software.wings.sm.states.KubernetesDeploy;
import software.wings.sm.states.KubernetesDeployRollback;
import software.wings.sm.states.KubernetesSetup;
import software.wings.sm.states.KubernetesSetupRollback;
import software.wings.sm.states.KubernetesSteadyStateCheck;
import software.wings.sm.states.KubernetesSwapServiceSelectors;
import software.wings.sm.states.LogzAnalysisState;
import software.wings.sm.states.NewRelicDeploymentMarkerState;
import software.wings.sm.states.NewRelicState;
import software.wings.sm.states.PauseState;
import software.wings.sm.states.PhaseStepSubWorkflow;
import software.wings.sm.states.PhaseSubWorkflow;
import software.wings.sm.states.PrometheusState;
import software.wings.sm.states.RepeatState;
import software.wings.sm.states.RepeatState.RepeatStateExecutionData;
import software.wings.sm.states.ResourceConstraintState;
import software.wings.sm.states.RollingNodeSelectState;
import software.wings.sm.states.ScalyrState;
import software.wings.sm.states.ShellScriptState;
import software.wings.sm.states.SplunkState;
import software.wings.sm.states.SplunkV2State;
import software.wings.sm.states.StackDriverLogState;
import software.wings.sm.states.StackDriverState;
import software.wings.sm.states.StagingOriginalExecution;
import software.wings.sm.states.SubWorkflowState;
import software.wings.sm.states.SumoLogicAnalysisState;
import software.wings.sm.states.TemplatizedSecretManagerState;
import software.wings.sm.states.WaitState;
import software.wings.sm.states.azure.AzureVMSSDeployExecutionSummary;
import software.wings.sm.states.azure.AzureVMSSDeployState;
import software.wings.sm.states.azure.AzureVMSSDeployStateExecutionData;
import software.wings.sm.states.azure.AzureVMSSRollbackState;
import software.wings.sm.states.azure.AzureVMSSSetupExecutionSummary;
import software.wings.sm.states.azure.AzureVMSSSetupState;
import software.wings.sm.states.azure.AzureVMSSSetupStateExecutionData;
import software.wings.sm.states.azure.AzureVMSSSwitchRoutesRollbackState;
import software.wings.sm.states.azure.AzureVMSSSwitchRoutesState;
import software.wings.sm.states.azure.appservices.AzureAppServiceSlotSetupExecutionData;
import software.wings.sm.states.azure.appservices.AzureAppServiceSlotSetupExecutionSummary;
import software.wings.sm.states.azure.appservices.AzureAppServiceSlotShiftTrafficExecutionData;
import software.wings.sm.states.azure.appservices.AzureAppServiceSlotShiftTrafficExecutionSummary;
import software.wings.sm.states.azure.appservices.AzureAppServiceSlotSwapExecutionData;
import software.wings.sm.states.azure.appservices.AzureAppServiceSlotSwapExecutionSummary;
import software.wings.sm.states.azure.appservices.AzureWebAppSlotRollback;
import software.wings.sm.states.azure.appservices.AzureWebAppSlotSetup;
import software.wings.sm.states.azure.appservices.AzureWebAppSlotShiftTraffic;
import software.wings.sm.states.azure.appservices.AzureWebAppSlotSwap;
import software.wings.sm.states.collaboration.JiraCreateUpdate;
import software.wings.sm.states.collaboration.ServiceNowCreateUpdateState;
import software.wings.sm.states.customdeployment.InstanceFetchState;
import software.wings.sm.states.k8s.K8sApplyState;
import software.wings.sm.states.k8s.K8sBlueGreenDeploy;
import software.wings.sm.states.k8s.K8sCanaryDeploy;
import software.wings.sm.states.k8s.K8sDelete;
import software.wings.sm.states.k8s.K8sRollingDeploy;
import software.wings.sm.states.k8s.K8sRollingDeployRollback;
import software.wings.sm.states.k8s.K8sScale;
import software.wings.sm.states.k8s.K8sTrafficSplitState;
import software.wings.sm.states.pcf.MapRouteState;
import software.wings.sm.states.pcf.PcfDeployState;
import software.wings.sm.states.pcf.PcfPluginState;
import software.wings.sm.states.pcf.PcfRollbackState;
import software.wings.sm.states.pcf.PcfSetupState;
import software.wings.sm.states.pcf.PcfSwitchBlueGreenRoutes;
import software.wings.sm.states.pcf.UnmapRouteState;
import software.wings.sm.states.provision.ARMProvisionState;
import software.wings.sm.states.provision.ARMRollbackState;
import software.wings.sm.states.provision.AdjustTerraformProvisionState;
import software.wings.sm.states.provision.ApplyTerraformProvisionState;
import software.wings.sm.states.provision.ApplyTerraformState;
import software.wings.sm.states.provision.CloudFormationCreateStackState;
import software.wings.sm.states.provision.CloudFormationDeleteStackState;
import software.wings.sm.states.provision.CloudFormationRollbackStackState;
import software.wings.sm.states.provision.DestroyTerraformProvisionState;
import software.wings.sm.states.provision.ShellScriptProvisionState;
import software.wings.sm.states.provision.TerraformRollbackState;
import software.wings.sm.states.provision.TerragruntApplyState;
import software.wings.sm.states.provision.TerragruntDestroyState;
import software.wings.sm.states.provision.TerragruntRollbackState;
import software.wings.sm.states.rancher.RancherK8sBlueGreenDeploy;
import software.wings.sm.states.rancher.RancherK8sCanaryDeploy;
import software.wings.sm.states.rancher.RancherK8sDelete;
import software.wings.sm.states.rancher.RancherK8sRollingDeploy;
import software.wings.sm.states.rancher.RancherK8sRollingDeployRollback;
import software.wings.sm.states.rancher.RancherKubernetesSwapServiceSelectors;
import software.wings.sm.states.rancher.RancherResolveState;
import software.wings.sm.states.spotinst.SpotInstDeployState;
import software.wings.sm.states.spotinst.SpotInstDeployStateExecutionData;
import software.wings.sm.states.spotinst.SpotInstListenerUpdateRollbackState;
import software.wings.sm.states.spotinst.SpotInstListenerUpdateState;
import software.wings.sm.states.spotinst.SpotInstListenerUpdateStateExecutionData;
import software.wings.sm.states.spotinst.SpotInstRollbackState;
import software.wings.sm.states.spotinst.SpotInstServiceSetup;
import software.wings.sm.states.spotinst.SpotInstSetupExecutionSummary;
import software.wings.sm.states.spotinst.SpotInstSetupStateExecutionData;
import software.wings.sm.states.spotinst.SpotinstDeployExecutionSummary;
import software.wings.sm.states.spotinst.SpotinstTrafficShiftAlbDeployExecutionData;
import software.wings.sm.states.spotinst.SpotinstTrafficShiftAlbDeployState;
import software.wings.sm.states.spotinst.SpotinstTrafficShiftAlbRollbackSwitchRoutesState;
import software.wings.sm.states.spotinst.SpotinstTrafficShiftAlbSetupExecutionData;
import software.wings.sm.states.spotinst.SpotinstTrafficShiftAlbSetupState;
import software.wings.sm.states.spotinst.SpotinstTrafficShiftAlbSwapRoutesExecutionData;
import software.wings.sm.states.spotinst.SpotinstTrafficShiftAlbSwitchRoutesState;
import software.wings.timescale.framework.TimeScaleEntityIndexState;
import software.wings.verification.CVActivityLog;
import software.wings.verification.CVConfiguration;
import software.wings.verification.VerificationDataAnalysisResponse;
import software.wings.verification.VerificationStateAnalysisExecutionData;
import software.wings.verification.apm.APMCVServiceConfiguration;
import software.wings.verification.appdynamics.AppDynamicsCVServiceConfiguration;
import software.wings.verification.cloudwatch.CloudWatchCVServiceConfiguration;
import software.wings.verification.datadog.DatadogCVServiceConfiguration;
import software.wings.verification.datadog.DatadogLogCVConfiguration;
import software.wings.verification.dynatrace.DynaTraceCVServiceConfiguration;
import software.wings.verification.instana.InstanaCVConfiguration;
import software.wings.verification.log.BugsnagCVConfiguration;
import software.wings.verification.log.CustomLogCVServiceConfiguration;
import software.wings.verification.log.ElkCVConfiguration;
import software.wings.verification.log.LogsCVConfiguration;
import software.wings.verification.log.SplunkCVConfiguration;
import software.wings.verification.log.StackdriverCVConfiguration;
import software.wings.verification.newrelic.NewRelicCVServiceConfiguration;
import software.wings.verification.prometheus.PrometheusCVServiceConfiguration;
import software.wings.verification.stackdriver.StackDriverMetricCVConfiguration;
import software.wings.yaml.YamlHistory;
import software.wings.yaml.YamlVersion;
import software.wings.yaml.errorhandling.GitSyncError;
import software.wings.yaml.errorhandling.GitToHarnessErrorDetails;
import software.wings.yaml.errorhandling.HarnessToGitErrorDetails;
import software.wings.yaml.gitSync.GitFileActivity;
import software.wings.yaml.gitSync.GitFileProcessingSummary;
import software.wings.yaml.gitSync.GitSyncMetadata;
import software.wings.yaml.gitSync.GitSyncWebhook;
import software.wings.yaml.gitSync.YamlChangeSet;
import software.wings.yaml.gitSync.beans.YamlGitConfig;

import java.security.Principal;
import java.util.Set;

@OwnedBy(PL)
public class ManagerMorphiaRegistrar implements MorphiaRegistrar {
  private String cf = "helpers.ext.cloudformation.";

  @Override
  public void registerClasses(Set<Class> set) {
    set.add(Account.class);
    set.add(AcrArtifactStream.class);
    set.add(ActionableNotification.class);
    set.add(Activity.class);
    set.add(AggregateResult.class);
    set.add(Alert.class);
    set.add(AlertNotificationRule.class);
    set.add(AmazonS3ArtifactStream.class);
    set.add(AmiArtifactStream.class);
    set.add(AnalysisContext.class);
    set.add(ApiKeyEntry.class);
    set.add(APMCVServiceConfiguration.class);
    set.add(AppDynamicsCVServiceConfiguration.class);
    set.add(Application.class);
    set.add(ApplicationManifest.class);
    set.add(ApprovalNotification.class);
    set.add(ApprovalPollingJobEntity.class);
    set.add(ArtifactoryArtifactStream.class);
    set.add(ArtifactStream.class);
    set.add(ArtifactStreamWithOnlyAuditNeededData.class);
    set.add(AuditHeader.class);
    set.add(AuditPreference.class);
    set.add(AuditRecord.class);
    set.add(AuthToken.class);
    set.add(AwsAmiInfrastructureMapping.class);
    set.add(AzureVMSSInfrastructureMapping.class);
    set.add(AzureWebAppInfrastructureMapping.class);
    set.add(AwsInfrastructureMapping.class);
    set.add(AwsLambdaInfraStructureMapping.class);
    set.add(AzureArtifactsArtifactStream.class);
    set.add(AzureMachineImageArtifactStream.class);
    set.add(AzureInfrastructureMapping.class);
    set.add(AzureKubernetesInfrastructureMapping.class);
    set.add(BambooArtifactStream.class);
    set.add(BarrierInstance.class);
    set.add(Base.class);
    set.add(BugsnagCVConfiguration.class);
    set.add(CECloudAccountOld.class);
    set.add(CECommunications.class);
    set.add(CESlackWebhook.class);
    set.add(CloudFormationInfrastructureProvisioner.class);
    set.add(CloudFormationRollbackConfig.class);
    set.add(CloudWatchCVServiceConfiguration.class);
    set.add(ClusterRecord.class);
    set.add(CodeDeployInfrastructureMapping.class);
    set.add(CollectEvent.class);
    set.add(Command.class);
    set.add(CommandEntity.class);
    set.add(CommandVersionEntity.class);
    set.add(Comparable.class);
    set.add(ContainerDeploymentInfo.class);
    set.add(ContainerInfrastructureMapping.class);
    set.add(ContainerTask.class);
    set.add(ContinuousVerificationExecutionMetaData.class);
    set.add(CustomArtifactStream.class);
    set.add(CustomLogCVServiceConfiguration.class);
    set.add(CVConfiguration.class);
    set.add(CVFeedbackRecord.class);
    set.add(CustomInfrastructureMapping.class);
    set.add(DashboardSettings.class);
    set.add(DatadogCVServiceConfiguration.class);
    set.add(DatadogLogCVConfiguration.class);
    set.add(DelegateSequenceConfig.class);
    set.add(DeploymentEvent.class);
    set.add(DeploymentPreference.class);
    set.add(DeploymentReconRecord.class);
    set.add(DeploymentSpecification.class);
    set.add(DeploymentSummary.class);
    set.add(DeploymentTimeSeriesEvent.class);
    set.add(DeploymentStepTimeSeriesEvent.class);
    set.add(ExecutionInterruptTimeSeriesEvent.class);
    set.add(DirectKubernetesInfrastructureMapping.class);
    set.add(RancherKubernetesInfrastructureMapping.class);
    set.add(DockerArtifactStream.class);
    set.add(DynaTraceCVServiceConfiguration.class);
    set.add(EcrArtifactStream.class);
    set.add(EcsContainerTask.class);
    set.add(EcsInfrastructureMapping.class);
    set.add(EcsServiceSpecification.class);
    set.add(ElasticsearchBulkMigrationJob.class);
    set.add(ElkCVConfiguration.class);
    set.add(EmailData.class);
    set.add(EmailVerificationToken.class);
    set.add(EntityVersion.class);
    set.add(EntityVersionCollection.class);
    set.add(EntityYamlRecord.class);
    set.add(Environment.class);
    set.add(ExecutionEvent.class);
    set.add(ExecutionInterrupt.class);
    set.add(ExperimentalLogMLAnalysisRecord.class);
    set.add(ExperimentalMessageComparisonResult.class);
    set.add(ExperimentalMetricAnalysisRecord.class);
    set.add(ExportExecutionsNotification.class);
    set.add(ExportExecutionsRequest.class);
    set.add(ExternalServiceAuthToken.class);
    set.add(FailureNotification.class);
    set.add(GcpBillingAccount.class);
    set.add(GCPBillingJobEntity.class);
    set.add(GcpKubernetesInfrastructureMapping.class);
    set.add(GcpOrganization.class);
    set.add(GcpServiceAccount.class);
    set.add(GcpServiceAccountOld.class);
    set.add(GCPUsageReport.class);
    set.add(GcrArtifactStream.class);
    set.add(GcsArtifactStream.class);
    set.add(GcsFileMetadata.class);
    set.add(GitCommit.class);
    set.add(GitFileActivity.class);
    set.add(GitFileActivitySummary.class);
    set.add(GitSyncError.class);
    set.add(GitSyncWebhook.class);
    set.add(GovernanceConfig.class);
    set.add(HarnessTag.class);
    set.add(HarnessTagLink.class);
    set.add(HarnessUserGroup.class);
    set.add(HelmChartSpecification.class);
    set.add(Idempotent.class);
    set.add(ImportedTemplate.class);
    set.add(InformationNotification.class);
    set.add(InfraMappingWithOnlyAuditNeededData.class);
    set.add(InfrastructureDefinition.class);
    set.add(InfrastructureMapping.class);
    set.add(InfrastructureProvisioner.class);
    set.add(InstanaCVConfiguration.class);
    set.add(Instance.class);
    set.add(InstanceChangeEvent.class);
    set.add(InstanceEvent.class);
    set.add(InstanceStatsSnapshot.class);
    set.add(InstanceSyncPerpetualTaskInfo.class);
    set.add(JenkinsArtifactStream.class);
    set.add(KubernetesContainerTask.class);
    set.add(LabeledLogRecord.class);
    set.add(LambdaSpecification.class);
    set.add(LdapSettings.class);
    set.add(LearningEngineAnalysisTask.class);
    set.add(LearningEngineExperimentalAnalysisTask.class);
    set.add(License.class);
    set.add(LogDataRecord.class);
    set.add(LoginSettings.class);
    set.add(LogMLAnalysisRecord.class);
    set.add(LogMLFeedbackRecord.class);
    set.add(LogsCVConfiguration.class);
    set.add(ManagerConfiguration.class);
    set.add(ManifestFile.class);
    set.add(ManualSyncJob.class);
    set.add(MarketPlace.class);
    set.add(MetricAnalysisRecord.class);
    set.add(MLExperiments.class);
    set.add(NewRelicCVServiceConfiguration.class);
    set.add(NewRelicMetricAnalysisRecord.class);
    set.add(NexusArtifactStream.class);
    set.add(Notification.class);
    set.add(NotificationBatch.class);
    set.add(NotificationGroup.class);
    set.add(NotificationReceiverInfo.class);
    set.add(NotificationRulesStatus.class);
    set.add(OauthSettings.class);
    set.add(PcfInfrastructureMapping.class);
    set.add(PcfServiceSpecification.class);
    set.add(Permit.class);
    set.add(Personalization.class);
    set.add(PhysicalInfrastructureMapping.class);
    set.add(PhysicalInfrastructureMappingBase.class);
    set.add(PhysicalInfrastructureMappingWinRm.class);
    set.add(Pipeline.class);
    set.add(PipelineExecution.class);
    set.add(PipelineGovernanceConfig.class);
    set.add(Preference.class);
    set.add(Principal.class);
    set.add(PricingProfile.class);
    set.add(PrometheusCVServiceConfiguration.class);
    set.add(ProvisionerWithOnlyAuditNeededData.class);
    set.add(ResourceConstraintInstance.class);
    set.add(PruneEvent.class);
    set.add(ResourceConstraintNotification.class);
    set.add(ResourceLookup.class);
    set.add(Role.class);
    set.add(SamlSettings.class);
    set.add(Schema.class);
    set.add(SearchDistributedLock.class);
    set.add(SearchEntityIndexState.class);
    set.add(SearchSourceEntitySyncState.class);
    set.add(SegmentGroupEventJobContext.class);
    set.add(ServerlessInstance.class);
    set.add(ServerlessInstanceStats.class);
    set.add(Service.class);
    set.add(ServiceCommand.class);
    set.add(ServiceInstance.class);
    set.add(ServiceTemplate.class);
    set.add(ConfigFile.class);
    set.add(SftpArtifactStream.class);
    set.add(ShellScriptInfrastructureProvisioner.class);
    set.add(SmbArtifactStream.class);
    set.add(SplunkCVConfiguration.class);
    set.add(SSOSettings.class);
    set.add(StackdriverCVConfiguration.class);
    set.add(StackDriverMetricCVConfiguration.class);
    set.add(StateExecutionInstance.class);
    set.add(StateMachine.class);
    set.add(SupervisedTrainingStatus.class);
    set.add(SupervisedTSThreshold.class);
    set.add(SyncStatus.class);
    set.add(SystemCatalog.class);
    set.add(TagAware.class);
    set.add(Template.class);
    set.add(TemplateFolder.class);
    set.add(TemplateGallery.class);
    set.add(TemplateVersion.class);
    set.add(TerraformConfig.class);
    set.add(TerraformInfrastructureProvisioner.class);
    set.add(TerragruntConfig.class);
    set.add(TerragruntInfrastructureProvisioner.class);
    set.add(TimeScaleEntityIndexState.class);
    set.add(TimeSeriesDataRecord.class);
    set.add(TimeSeriesKeyTransactions.class);
    set.add(TimeSeriesMetricGroup.class);
    set.add(TimeSeriesMetricTemplates.class);
    set.add(TimeSeriesMLAnalysisRecord.class);
    set.add(TimeSeriesMLScores.class);
    set.add(TimeSeriesMLTransactionThresholds.class);
    set.add(TimeSeriesRawData.class);
    set.add(TimeSeriesRiskSummary.class);
    set.add(Trigger.class);
    set.add(TriggerExecution.class);
    set.add(User.class);
    set.add(UserDataSpecification.class);
    set.add(UserGroup.class);
    set.add(UserInvite.class);
    set.add(VersionedTemplate.class);
    set.add(Whitelist.class);
    set.add(Workflow.class);
    set.add(WorkflowExecution.class);
    set.add(WorkflowExecutionBaseline.class);
    set.add(YamlChangeSet.class);
    set.add(YamlHistory.class);
    set.add(YamlSuccessfulChange.class);
    set.add(YamlVersion.class);
    set.add(GCPMarketplaceCustomer.class);
    set.add(DeletedEntity.class);
    set.add(ARMInfrastructureProvisioner.class);
    set.add(AccessRequest.class);
    set.add(ArtifactView.class);
    set.add(LookerEntityReconRecord.class);
    set.add(InstanceSyncTaskDetails.class);
    set.add(MigratedAccountTracker.class);
    set.add(YamlGitConfig.class);
    set.add(SettingAttribute.class);
    set.add(Artifact.class);
    set.add(BaseFile.class);
    set.add(AppContainer.class);
    set.add(LongerDataRetentionState.class);
    set.add(ThirdPartyApiCallLog.class);
    set.add(CVActivityLog.class);
    set.add(Log.class);
    set.add(InstanceSyncPTInfoBackup.class);
    set.add(HelmChart.class);
    set.add(NewRelicMetricDataRecord.class);
  }

  @Override
  public void registerImplementationClasses(MorphiaRegistrarHelperPut h, MorphiaRegistrarHelperPut w) {
    h.put("ccm.cluster.entities.AzureKubernetesCluster", AzureKubernetesCluster.class);
    h.put("ccm.cluster.entities.DirectKubernetesCluster", DirectKubernetesCluster.class);
    h.put("ccm.cluster.entities.EcsCluster", EcsCluster.class);
    h.put("ccm.cluster.entities.GcpKubernetesCluster", GcpKubernetesCluster.class);
    h.put("marketplace.gcp.events.ProcurementPubsubMessage", ProcurementPubsubMessage.class);

    // Redesign Classes
    w.put("api.AmiStepExecutionSummary", AmiStepExecutionSummary.class);
    w.put("api.ApprovalStateExecutionData", ApprovalStateExecutionData.class);
    w.put("api.helm.ServiceHelmElements", ServiceHelmElements.class);
    w.put("api.artifact.ServiceArtifactElements", ServiceArtifactElements.class);
    w.put("api.artifact.ServiceArtifactVariableElements", ServiceArtifactVariableElements.class);
    w.put("api.ArtifactCollectionExecutionData", ArtifactCollectionExecutionData.class);
    w.put("api.AwsAmiDeployStateExecutionData", AwsAmiDeployStateExecutionData.class);
    w.put("api.AwsAmiSetupExecutionData", AwsAmiSetupExecutionData.class);
    w.put("api.AwsAmiSwitchRoutesStateExecutionData", AwsAmiSwitchRoutesStateExecutionData.class);
    w.put("api.AwsAutoScalingGroupDeploymentInfo", AwsAutoScalingGroupDeploymentInfo.class);
    w.put("api.AwsCodeDeployDeploymentInfo", AwsCodeDeployDeploymentInfo.class);
    w.put("api.BarrierExecutionData", BarrierExecutionData.class);
    w.put("api.BarrierStepExecutionSummary", BarrierStepExecutionSummary.class);
    w.put("api.CommandStateExecutionData", CommandStateExecutionData.class);
    w.put("api.CommandStepExecutionSummary", CommandStepExecutionSummary.class);
    w.put("api.ContainerDeploymentInfoWithLabels", ContainerDeploymentInfoWithLabels.class);
    w.put("api.ContainerDeploymentInfoWithNames", ContainerDeploymentInfoWithNames.class);
    w.put("api.ecs.EcsListenerUpdateExecutionSummary", EcsListenerUpdateExecutionSummary.class);
    w.put("api.ecs.EcsListenerUpdateStateExecutionData", EcsListenerUpdateStateExecutionData.class);
    w.put("api.ecs.EcsRoute53WeightUpdateStateExecutionData", EcsRoute53WeightUpdateStateExecutionData.class);
    w.put("api.EcsStepExecutionSummary", EcsStepExecutionSummary.class);
    w.put("api.ElbStateExecutionData", ElbStateExecutionData.class);
    w.put("api.EmailStateExecutionData", EmailStateExecutionData.class);
    w.put("api.EnvStateExecutionData", EnvStateExecutionData.class);
    w.put("api.HelmDeployStateExecutionData", HelmDeployStateExecutionData.class);
    w.put("api.HelmSetupExecutionSummary", HelmSetupExecutionSummary.class);
    w.put("api.HttpStateExecutionData", HttpStateExecutionData.class);
    w.put("api.instancedetails.InstanceInfoVariables", InstanceInfoVariables.class);
    w.put("api.JenkinsExecutionData", JenkinsExecutionData.class);
    w.put("api.k8s.k8sApplicationManifestInfo", K8sApplicationManifestSourceInfo.class);
    w.put("api.k8s.k8sGitConfigMapInfo", K8sGitConfigMapInfo.class);
    w.put("api.k8s.k8sGitFetchInfo", K8sGitFetchInfo.class);
    w.put("api.k8s.K8sGitInfo", K8sGitInfo.class);
    w.put("api.k8s.K8sHelmElement", K8sHelmDeploymentElement.class);
    w.put("api.k8s.K8sCanaryDeleteServiceElement", K8sCanaryDeleteServiceElement.class);
    w.put("api.k8s.K8sExecutionSummary", K8sExecutionSummary.class);
    w.put("api.k8s.K8sStateExecutionData", K8sStateExecutionData.class);
    w.put("api.K8sDeploymentInfo", K8sDeploymentInfo.class);
    w.put("api.KubernetesSteadyStateCheckExecutionData", KubernetesSteadyStateCheckExecutionData.class);
    w.put("api.KubernetesSteadyStateCheckExecutionSummary", KubernetesSteadyStateCheckExecutionSummary.class);
    w.put("api.KubernetesSwapServiceSelectorsExecutionData", KubernetesSwapServiceSelectorsExecutionData.class);
    w.put("api.lambda.AwsLambdaDeploymentInfo", AwsLambdaDeploymentInfo.class);
    w.put("api.pcf.DeploySweepingOutputPcf", DeploySweepingOutputPcf.class);
    w.put("api.pcf.InfoVariables", InfoVariables.class);
    w.put("api.pcf.PcfDeployExecutionSummary", PcfDeployExecutionSummary.class);
    w.put("api.pcf.PcfDeployStateExecutionData", PcfDeployStateExecutionData.class);
    w.put("api.pcf.PcfPluginExecutionSummary", PcfPluginExecutionSummary.class);
    w.put("api.pcf.PcfPluginStateExecutionData", PcfPluginStateExecutionData.class);
    w.put("api.pcf.PcfRouteSwapExecutionSummary", PcfRouteSwapExecutionSummary.class);
    w.put("api.pcf.PcfRouteUpdateStateExecutionData", PcfRouteUpdateStateExecutionData.class);
    w.put("api.pcf.PcfSetupExecutionSummary", PcfSetupExecutionSummary.class);
    w.put("api.pcf.PcfSetupStateExecutionData", PcfSetupStateExecutionData.class);
    w.put("api.pcf.SetupSweepingOutputPcf", SetupSweepingOutputPcf.class);
    w.put("api.pcf.SwapRouteRollbackSweepingOutputPcf", SwapRouteRollbackSweepingOutputPcf.class);
    w.put("api.PcfDeploymentInfo", PcfDeploymentInfo.class);
    w.put("api.PhaseExecutionData", PhaseExecutionData.class);
    w.put("api.PhaseStepExecutionData", PhaseStepExecutionData.class);
    w.put("api.ResourceConstraintExecutionData", ResourceConstraintExecutionData.class);
    w.put("api.ResourceConstraintStepExecutionSummary", ResourceConstraintStepExecutionSummary.class);
    w.put("api.ARMStateExecutionData", ARMStateExecutionData.class);
    w.put("api.SelectedNodeExecutionData", SelectedNodeExecutionData.class);
    w.put("api.SelectNodeStepExecutionSummary", SelectNodeStepExecutionSummary.class);
    w.put("api.ServiceArtifactElements", ServiceArtifactElements.class);
    w.put("api.SkipStateExecutionData", SkipStateExecutionData.class);
    w.put("api.SpotinstAmiDeploymentInfo", SpotinstAmiDeploymentInfo.class);
    w.put("api.AzureVMSSDeploymentInfo", AzureVMSSDeploymentInfo.class);
    w.put("api.AzureWebAppDeploymentInfo", AzureWebAppDeploymentInfo.class);
    w.put("api.terragrunt.TerragruntApplyMarkerParam", TerragruntApplyMarkerParam.class);
    w.put("api.TerraformApplyMarkerParam", TerraformApplyMarkerParam.class);
    w.put("audit.EntityAuditRecord", EntityAuditRecord.class);
    w.put("beans.alert.ApprovalNeededAlert", ApprovalNeededAlert.class);
    w.put("beans.RuntimeInputsConfig", RuntimeInputsConfig.class);
    w.put("beans.alert.ArtifactCollectionFailedAlert", ArtifactCollectionFailedAlert.class);
    w.put("beans.alert.cv.ContinuousVerificationAlertData", ContinuousVerificationAlertData.class);
    w.put("beans.alert.cv.ContinuousVerificationDataCollectionAlert", ContinuousVerificationDataCollectionAlert.class);
    w.put("beans.alert.DelegatesDownAlert", DelegatesDownAlert.class);
    w.put("beans.alert.DeploymentFreezeEventAlert", DeploymentFreezeEventAlert.class);
    w.put("beans.alert.DeploymentRateApproachingLimitAlert", DeploymentRateApproachingLimitAlert.class);
    w.put("beans.alert.EmailSendingFailedAlert", EmailSendingFailedAlert.class);
    w.put("beans.alert.GitConnectionErrorAlert", GitConnectionErrorAlert.class);
    w.put("beans.alert.GitSyncErrorAlert", GitSyncErrorAlert.class);
    w.put("beans.alert.InstanceUsageLimitAlert", InstanceUsageLimitAlert.class);
    w.put("beans.alert.InvalidSMTPConfigAlert", InvalidSMTPConfigAlert.class);
    w.put("beans.alert.KmsSetupAlert", KmsSetupAlert.class);
    w.put("beans.alert.ManifestCollectionFailedAlert", ManifestCollectionFailedAlert.class);
    w.put("beans.alert.ManualInterventionNeededAlert", ManualInterventionNeededAlert.class);
    w.put("beans.alert.ResourceUsageApproachingLimitAlert", ResourceUsageApproachingLimitAlert.class);
    w.put("beans.alert.SettingAttributeValidationFailedAlert", SettingAttributeValidationFailedAlert.class);
    w.put("beans.alert.SSOSyncFailedAlert", SSOSyncFailedAlert.class);
    w.put("beans.alert.UsageLimitExceededAlert", UsageLimitExceededAlert.class);
    w.put("persistence.artifact.ArtifactFile", ArtifactFile.class);
    w.put("beans.BasicOrchestrationWorkflow", BasicOrchestrationWorkflow.class);
    w.put("beans.BlueGreenOrchestrationWorkflow", BlueGreenOrchestrationWorkflow.class);
    w.put("beans.BuildWorkflow", BuildWorkflow.class);
    w.put("beans.CanaryOrchestrationWorkflow", CanaryOrchestrationWorkflow.class);
    w.put("beans.CanaryWorkflowExecutionAdvisor", CanaryWorkflowExecutionAdvisor.class);
    w.put("beans.command.Command", Command.class);
    w.put("beans.container.EcsContainerTask", EcsContainerTask.class);
    w.put("beans.container.KubernetesContainerTask", KubernetesContainerTask.class);
    w.put("beans.EcsBlueGreenOrchestrationWorkflow", EcsBlueGreenOrchestrationWorkflow.class);
    w.put("beans.EntityVersion", EntityVersion.class);
    w.put("beans.infrastructure.instance.info.AutoScalingGroupInstanceInfo", AutoScalingGroupInstanceInfo.class);
    w.put("beans.infrastructure.instance.info.AwsLambdaInstanceInfo", AwsLambdaInstanceInfo.class);
    w.put("beans.infrastructure.instance.info.CodeDeployInstanceInfo", CodeDeployInstanceInfo.class);
    w.put("beans.infrastructure.instance.info.Ec2InstanceInfo", Ec2InstanceInfo.class);
    w.put("beans.infrastructure.instance.info.PcfInstanceInfo", PcfInstanceInfo.class);
    w.put("beans.infrastructure.instance.info.PhysicalHostInstanceInfo", PhysicalHostInstanceInfo.class);
    w.put("beans.infrastructure.instance.info.SpotinstAmiInstanceInfo", SpotinstAmiInstanceInfo.class);
    w.put("beans.infrastructure.instance.info.AzureVMSSInstanceInfo", AzureVMSSInstanceInfo.class);
    w.put("beans.infrastructure.instance.info.AzureWebAppInstanceInfo", AzureWebAppInstanceInfo.class);
    w.put("beans.MultiServiceOrchestrationWorkflow", MultiServiceOrchestrationWorkflow.class);
    w.put("beans.RollingOrchestrationWorkflow", RollingOrchestrationWorkflow.class);
    w.put("beans.template.artifactsource.ArtifactSourceTemplate", ArtifactSourceTemplate.class);
    w.put("beans.template.artifactsource.CustomArtifactSourceTemplate", CustomArtifactSourceTemplate.class);
    w.put("beans.template.command.HttpTemplate", HttpTemplate.class);
    w.put("beans.template.command.PcfCommandTemplate", PcfCommandTemplate.class);
    w.put("beans.template.command.ShellScriptTemplate", ShellScriptTemplate.class);
    w.put("beans.template.command.SshCommandTemplate", SshCommandTemplate.class);
    w.put("beans.trigger.ArtifactTriggerCondition", ArtifactTriggerCondition.class);
    w.put("beans.trigger.NewInstanceTriggerCondition", NewInstanceTriggerCondition.class);
    w.put("beans.trigger.PipelineTriggerCondition", PipelineTriggerCondition.class);
    w.put("beans.trigger.ScheduledTriggerCondition", ScheduledTriggerCondition.class);
    w.put("beans.trigger.WebHookTriggerCondition", WebHookTriggerCondition.class);
    w.put("beans.trigger.WorkflowAction", WorkflowAction.class);
    w.put("beans.yaml.GitSuccessFulChangeDetail", GitSuccessFulChangeDetail.class);
    w.put("beans.yaml.HarnessSuccessFulChangeDetail", HarnessSuccessFulChangeDetail.class);
    w.put("collect.ArtifactCollectionCallback", ArtifactCollectionCallback.class);
    w.put("delegatetasks.buildsource.BuildSourceCallback", BuildSourceCallback.class);
    w.put("delegatetasks.buildsource.BuildSourceCleanupCallback", BuildSourceCleanupCallback.class);
    w.put("helpers.ext.cloudformation.CloudFormationCompletionFlag", CloudFormationCompletionFlag.class);
    w.put("infra.AwsAmiInfrastructure", AwsAmiInfrastructure.class);
    w.put("infra.AzureVMSSInfra", AzureVMSSInfra.class);
    w.put("infra.AzureWebAppInfra", AzureWebAppInfra.class);
    w.put("infra.AwsEcsInfrastructure", AwsEcsInfrastructure.class);
    w.put("infra.AwsInstanceInfrastructure", AwsInstanceInfrastructure.class);
    w.put("infra.AwsLambdaInfrastructure", AwsLambdaInfrastructure.class);
    w.put("infra.AzureInstanceInfrastructure", AzureInstanceInfrastructure.class);
    w.put("infra.AzureKubernetesService", AzureKubernetesService.class);
    w.put("infra.CodeDeployInfrastructure", CodeDeployInfrastructure.class);
    w.put("infra.DirectKubernetesInfrastructure", DirectKubernetesInfrastructure.class);
    w.put("infra.GoogleKubernetesEngine", GoogleKubernetesEngine.class);
    w.put("infra.PcfInfraStructure", PcfInfraStructure.class);
    w.put("infra.PhysicalInfra", PhysicalInfra.class);
    w.put("infra.PhysicalInfraWinrm", PhysicalInfraWinrm.class);
    w.put("infra.CustomInfrastructure", CustomInfrastructure.class);
    w.put("resources.DelegateFileResource$FileIdempotentResult", FileIdempotentResult.class);
    w.put("service.impl.analysis.DataCollectionCallback", DataCollectionCallback.class);
    w.put("service.impl.analysis.LogAnalysisExecutionData", NotFoundClass.class);
    w.put("service.impl.email.EmailNotificationCallBack", EmailNotificationCallBack.class);
    w.put("service.impl.event.AccountEntityEvent", AccountEntityEvent.class);
    w.put("service.impl.event.AlertEvent", AlertEvent.class);
    w.put("service.impl.event.timeseries.TimeSeriesBatchEventInfo", TimeSeriesBatchEventInfo.class);
    w.put("service.impl.event.timeseries.TimeSeriesEventInfo", TimeSeriesEventInfo.class);
    w.put("service.impl.newrelic.MetricAnalysisExecutionData", NotFoundClass.class);
    w.put("service.impl.newrelic.NewRelicMarkerExecutionData", NewRelicMarkerExecutionData.class);
    w.put("service.impl.splunk.SplunkAnalysisCluster", SplunkAnalysisCluster.class);
    w.put("service.impl.trigger.TriggerCallback", TriggerCallback.class);
    w.put("service.impl.trigger.TriggerServiceImpl$TriggerIdempotentResult", TriggerIdempotentResult.class);
    w.put("service.impl.WorkflowExecutionUpdate", WorkflowExecutionUpdate.class);
    w.put("service.impl.yaml.GitCommandCallback", GitCommandCallback.class);
    w.put("sm.AwsLambdaVerification", AwsLambdaVerification.class);
    w.put("sm.ElementNotifyResponseData", ElementNotifyResponseData.class);
    w.put("sm.ExecutionResumeAllCallback", ExecutionResumeAllCallback.class);
    w.put("sm.ExecutionStatusData", ExecutionStatusData.class);
    w.put("sm.ExecutionWaitCallback", ExecutionWaitCallback.class);
    w.put("sm.ExecutionWaitRetryCallback", ExecutionWaitRetryCallback.class);
    w.put("sm.PhaseExecutionSummary", PhaseExecutionSummary.class);
    w.put("sm.PhaseStepExecutionSummary", PhaseStepExecutionSummary.class);
    w.put("sm.ResourceConstraintStatusData", ResourceConstraintStatusData.class);
    w.put("sm.StateMachineResumeCallback", StateMachineResumeCallback.class);
    w.put("sm.PipelineContinueWithInputsCallback", PipelineContinueWithInputsCallback.class);
    w.put("sm.states.APMVerificationState", APMVerificationState.class);
    w.put("sm.states.AppDynamicsState", AppDynamicsState.class);
    w.put("sm.states.ApprovalResumeState", ApprovalResumeState.class);
    w.put("sm.states.ApprovalState", ApprovalState.class);
    w.put("sm.states.ArtifactCollectLoopState", ArtifactCollectLoopState.class);
    w.put("sm.states.ArtifactCheckState", ArtifactCheckState.class);
    w.put("sm.states.ArtifactCollectionState", ArtifactCollectionState.class);
    w.put("sm.states.AwsAmiRollbackSwitchRoutesState", AwsAmiRollbackSwitchRoutesState.class);
    w.put("sm.states.AwsAmiServiceDeployState", AwsAmiServiceDeployState.class);
    w.put("sm.states.AwsAmiServiceRollback", AwsAmiServiceRollback.class);
    w.put("sm.states.AwsAmiServiceSetup", AwsAmiServiceSetup.class);
    w.put("sm.states.AwsAmiSwitchRoutesState", AwsAmiSwitchRoutesState.class);
    w.put("sm.states.AwsAmiServiceTrafficShiftAlbSetup", AwsAmiServiceTrafficShiftAlbSetup.class);
    w.put("sm.states.AwsAmiServiceTrafficShiftAlbDeployState", AwsAmiServiceTrafficShiftAlbDeployState.class);
    w.put("sm.states.AwsAmiTrafficShiftAlbSwitchRoutesState", AwsAmiTrafficShiftAlbSwitchRoutesState.class);
    w.put("sm.states.AwsAmiRollbackTrafficShiftAlbSwitchRoutesState",
        AwsAmiRollbackTrafficShiftAlbSwitchRoutesState.class);
    w.put("sm.states.AwsCodeDeployRollback", AwsCodeDeployRollback.class);
    w.put("sm.states.AwsCodeDeployState", AwsCodeDeployState.class);
    w.put("sm.states.AwsLambdaRollback", AwsLambdaRollback.class);
    w.put("sm.states.AwsLambdaState", AwsLambdaState.class);
    w.put("sm.states.AwsNodeSelectState", AwsNodeSelectState.class);
    w.put("sm.states.CollectRemainingInstancesState", CollectRemainingInstancesState.class);
    w.put("sm.states.AzureNodeSelectState", AzureNodeSelectState.class);
    w.put("sm.states.BambooState", BambooState.class);
    w.put("sm.states.BarrierState", BarrierState.class);
    w.put("sm.states.BugsnagState", BugsnagState.class);
    w.put("sm.states.CloudWatchState", CloudWatchState.class);
    w.put("sm.states.collaboration.JiraCreateUpdate", JiraCreateUpdate.class);
    w.put("sm.states.collaboration.ServiceNowCreateUpdateState", ServiceNowCreateUpdateState.class);
    w.put("sm.states.CommandState", CommandState.class);
    w.put("sm.states.CustomLogVerificationState", CustomLogVerificationState.class);
    w.put("sm.states.DatadogLogState", DatadogLogState.class);
    w.put("sm.states.DatadogState", DatadogState.class);
    w.put("sm.states.DatadogState$Metric", DatadogState.Metric.class);
    w.put("sm.states.DcNodeSelectState", DcNodeSelectState.class);
    w.put("sm.states.DynatraceState", DynatraceState.class);
    w.put("sm.states.EcsBGRollbackRoute53DNSWeightState", EcsBGRollbackRoute53DNSWeightState.class);
    w.put("sm.states.EcsBGUpdateListnerRollbackState", EcsBGUpdateListnerRollbackState.class);
    w.put("sm.states.EcsBGUpdateListnerState", EcsBGUpdateListnerState.class);
    w.put("sm.states.EcsBGUpdateRoute53DNSWeightState", EcsBGUpdateRoute53DNSWeightState.class);
    w.put("sm.states.EcsBlueGreenServiceSetup", EcsBlueGreenServiceSetup.class);
    w.put("sm.states.EcsBlueGreenServiceSetupRoute53DNS", EcsBlueGreenServiceSetupRoute53DNS.class);
    w.put("sm.states.EcsDaemonServiceSetup", EcsDaemonServiceSetup.class);
    w.put("sm.states.EcsServiceDeploy", EcsServiceDeploy.class);
    w.put("sm.states.EcsServiceRollback", EcsServiceRollback.class);
    w.put("sm.states.EcsServiceSetup", EcsServiceSetup.class);
    w.put("sm.states.EcsSetupRollback", EcsSetupRollback.class);
    w.put("sm.states.EcsRunTaskDeploy", EcsRunTaskDeploy.class);
    w.put("sm.states.EcsSteadyStateCheck", EcsSteadyStateCheck.class);
    w.put("sm.states.ElasticLoadBalancerState", ElasticLoadBalancerState.class);
    w.put("sm.states.ElkAnalysisState", ElkAnalysisState.class);
    w.put("sm.states.EmailState", EmailState.class);
    w.put("sm.states.EnvResumeState", EnvResumeState.class);
    w.put("sm.states.EnvLoopState", EnvLoopState.class);
    w.put("sm.states.EnvLoopResumeState", EnvLoopResumeState.class);
    w.put("sm.states.EnvState", EnvState.class);
    w.put("sm.states.EnvState$EnvExecutionResponseData", EnvExecutionResponseData.class);
    w.put("sm.states.ForkState", ForkState.class);
    w.put("sm.states.ForkState$ForkStateExecutionData", ForkStateExecutionData.class);
    w.put("sm.states.GcbState", GcbState.class);
    w.put("sm.states.GcpClusterSetup", GcpClusterSetup.class);
    w.put("sm.states.HelmDeployState", HelmDeployState.class);
    w.put("sm.states.HelmRollbackState", HelmRollbackState.class);
    w.put("sm.states.HttpState", HttpState.class);
    w.put("sm.states.InstanaState", InstanaState.class);
    w.put("sm.states.JenkinsState", JenkinsState.class);
    w.put("sm.states.k8s.K8sApplyState", K8sApplyState.class);
    w.put("sm.states.k8s.K8sBlueGreenDeploy", K8sBlueGreenDeploy.class);
    w.put("sm.states.k8s.K8sCanaryDeploy", K8sCanaryDeploy.class);
    w.put("sm.states.k8s.K8sDelete", K8sDelete.class);
    w.put("sm.states.k8s.K8sRollingDeploy", K8sRollingDeploy.class);
    w.put("sm.states.k8s.K8sRollingDeployRollback", K8sRollingDeployRollback.class);
    w.put("sm.states.k8s.K8sScale", K8sScale.class);
    w.put("sm.states.k8s.K8sTrafficSplitState", K8sTrafficSplitState.class);

    w.put("sm.states.rancher.RancherResolveState", RancherResolveState.class);
    w.put("sm.states.rancher.RancherK8sRollingDeploy", RancherK8sRollingDeploy.class);
    w.put("sm.states.rancher.RancherK8sRollingDeployRollback", RancherK8sRollingDeployRollback.class);
    w.put("sm.states.rancher.RancherK8sCanaryDeploy", RancherK8sCanaryDeploy.class);
    w.put("sm.states.rancher.RancherK8sDelete", RancherK8sDelete.class);
    w.put("sm.states.rancher.RancherK8sBlueGreenDeploy", RancherK8sBlueGreenDeploy.class);
    w.put("sm.states.rancher.RancherKubernetesSwapServiceSelectors", RancherKubernetesSwapServiceSelectors.class);

    w.put("sm.states.KubernetesDeploy", KubernetesDeploy.class);
    w.put("sm.states.KubernetesDeployRollback", KubernetesDeployRollback.class);
    w.put("sm.states.KubernetesSetup", KubernetesSetup.class);
    w.put("sm.states.KubernetesSetupRollback", KubernetesSetupRollback.class);
    w.put("sm.states.KubernetesSteadyStateCheck", KubernetesSteadyStateCheck.class);
    w.put("sm.states.KubernetesSwapServiceSelectors", KubernetesSwapServiceSelectors.class);
    w.put("sm.states.LogzAnalysisState", LogzAnalysisState.class);
    w.put("sm.states.NewRelicDeploymentMarkerState", NewRelicDeploymentMarkerState.class);
    w.put("sm.states.NewRelicState", NewRelicState.class);
    w.put("sm.states.PauseState", PauseState.class);
    w.put("sm.states.pcf.MapRouteState", MapRouteState.class);
    w.put("sm.states.pcf.PcfDeployState", PcfDeployState.class);
    w.put("sm.states.pcf.PcfPluginState", PcfPluginState.class);
    w.put("sm.states.pcf.PcfRollbackState", PcfRollbackState.class);
    w.put("sm.states.pcf.PcfSetupState", PcfSetupState.class);
    w.put("sm.states.pcf.PcfSwitchBlueGreenRoutes", PcfSwitchBlueGreenRoutes.class);
    w.put("sm.states.pcf.UnmapRouteState", UnmapRouteState.class);
    w.put("sm.states.PhaseStepSubWorkflow", PhaseStepSubWorkflow.class);
    w.put("sm.states.PhaseSubWorkflow", PhaseSubWorkflow.class);
    w.put("sm.states.PrometheusState", PrometheusState.class);
    w.put("sm.states.provision.AdjustTerraformProvisionState", AdjustTerraformProvisionState.class);
    w.put("sm.states.provision.ApplyTerraformProvisionState", ApplyTerraformProvisionState.class);
    w.put("sm.states.provision.ApplyTerraformState", ApplyTerraformState.class);
    w.put("sm.states.provision.CloudFormationCreateStackState", CloudFormationCreateStackState.class);
    w.put("sm.states.provision.CloudFormationDeleteStackState", CloudFormationDeleteStackState.class);
    w.put("sm.states.provision.CloudFormationRollbackStackState", CloudFormationRollbackStackState.class);
    w.put("sm.states.provision.DestroyTerraformProvisionState", DestroyTerraformProvisionState.class);
    w.put("sm.states.provision.ShellScriptProvisionState", ShellScriptProvisionState.class);
    w.put("sm.states.provision.TerraformRollbackState", TerraformRollbackState.class);
    w.put("sm.states.provision.TerragruntApplyState", TerragruntApplyState.class);
    w.put("sm.states.provision.TerragruntDestroyState", TerragruntDestroyState.class);
    w.put("sm.states.provision.TerragruntRollbackState", TerragruntRollbackState.class);
    w.put("sm.states.provision.ARMProvisionState", ARMProvisionState.class);
    w.put("sm.states.provision.ARMRollbackState", ARMRollbackState.class);
    w.put("sm.states.RepeatState", RepeatState.class);
    w.put("sm.states.RepeatState$RepeatStateExecutionData", RepeatStateExecutionData.class);
    w.put("sm.states.ResourceConstraintState", ResourceConstraintState.class);
    w.put("sm.states.RollingNodeSelectState", RollingNodeSelectState.class);
    w.put("sm.states.ScalyrState", ScalyrState.class);
    w.put("sm.states.ShellScriptState", ShellScriptState.class);
    w.put("sm.states.SplunkState", SplunkState.class);
    w.put("sm.states.SplunkV2State", SplunkV2State.class);
    w.put("sm.states.CVNGState", CVNGState.class);
    w.put("sm.states.StackDriverLogState", StackDriverLogState.class);
    w.put("sm.states.StackDriverState", StackDriverState.class);
    w.put("sm.states.StagingOriginalExecution", StagingOriginalExecution.class);
    w.put("sm.states.SubWorkflowState", SubWorkflowState.class);
    w.put("sm.states.SumoLogicAnalysisState", SumoLogicAnalysisState.class);
    w.put("sm.states.TemplatizedSecretManagerState", TemplatizedSecretManagerState.class);
    w.put("sm.states.WaitState", WaitState.class);
    w.put("sm.states.azure.AzureVMSSSetupState", AzureVMSSSetupState.class);
    w.put("sm.states.azure.AzureVMSSSetupStateExecutionData", AzureVMSSSetupStateExecutionData.class);
    w.put("sm.states.azure.AzureVMSSSetupExecutionSummary", AzureVMSSSetupExecutionSummary.class);
    w.put("sm.states.azure.AzureVMSSDeployState", AzureVMSSDeployState.class);
    w.put("sm.states.azure.AzureVMSSDeployStateExecutionData", AzureVMSSDeployStateExecutionData.class);
    w.put("sm.states.azure.AzureVMSSDeployExecutionSummary", AzureVMSSDeployExecutionSummary.class);
    w.put("sm.states.azure.AzureVMSSRollbackState", AzureVMSSRollbackState.class);
    w.put("sm.states.azure.AzureVMSSSwitchRoutesState", AzureVMSSSwitchRoutesState.class);
    w.put("sm.states.azure.AzureVMSSSwitchRoutesRollbackState", AzureVMSSSwitchRoutesRollbackState.class);
    w.put("sm.states.azure.appservices.AzureWebAppSlotSetup", AzureWebAppSlotSetup.class);
    w.put("sm.states.azure.appservices.AzureWebAppSlotSwap", AzureWebAppSlotSwap.class);
    w.put("sm.states.azure.appservices.AzureWebAppSlotShiftTraffic", AzureWebAppSlotShiftTraffic.class);
    w.put("sm.states.azure.appservices.AzureWebAppSlotRollback", AzureWebAppSlotRollback.class);
    w.put("sm.states.azure.appservices.AzureAppServiceSlotSetupExecutionData",
        AzureAppServiceSlotSetupExecutionData.class);
    w.put("sm.states.azure.appservices.AzureAppServiceSlotSetupExecutionSummary",
        AzureAppServiceSlotSetupExecutionSummary.class);
    w.put("sm.states.azure.appservices.AzureAppServiceSlotShiftTrafficExecutionData",
        AzureAppServiceSlotShiftTrafficExecutionData.class);
    w.put("sm.states.azure.appservices.AzureAppServiceSlotShiftTrafficExecutionSummary",
        AzureAppServiceSlotShiftTrafficExecutionSummary.class);
    w.put(
        "sm.states.azure.appservices.AzureAppServiceSlotSwapExecutionData", AzureAppServiceSlotSwapExecutionData.class);
    w.put("sm.states.azure.appservices.AzureAppServiceSlotSwapExecutionSummary",
        AzureAppServiceSlotSwapExecutionSummary.class);
    w.put("verification.apm.APMCVServiceConfiguration", APMCVServiceConfiguration.class);
    w.put("verification.appdynamics.AppDynamicsCVServiceConfiguration", AppDynamicsCVServiceConfiguration.class);
    w.put("verification.cloudwatch.CloudWatchCVServiceConfiguration", CloudWatchCVServiceConfiguration.class);
    w.put("verification.datadog.DatadogCVServiceConfiguration", DatadogCVServiceConfiguration.class);
    w.put("verification.datadog.DatadogLogCVConfiguration", DatadogLogCVConfiguration.class);
    w.put("verification.dynatrace.DynaTraceCVServiceConfiguration", DynaTraceCVServiceConfiguration.class);
    w.put("verification.instana.InstanaCVConfiguration", InstanaCVConfiguration.class);
    w.put("verification.log.BugsnagCVConfiguration", BugsnagCVConfiguration.class);
    w.put("verification.log.CustomLogCVServiceConfiguration", CustomLogCVServiceConfiguration.class);
    w.put("verification.log.ElkCVConfiguration", ElkCVConfiguration.class);
    w.put("verification.log.LogsCVConfiguration", LogsCVConfiguration.class);
    w.put("verification.log.SplunkCVConfiguration", SplunkCVConfiguration.class);
    w.put("verification.log.StackdriverCVConfiguration", StackdriverCVConfiguration.class);
    w.put("verification.newrelic.NewRelicCVServiceConfiguration", NewRelicCVServiceConfiguration.class);
    w.put("verification.prometheus.PrometheusCVServiceConfiguration", PrometheusCVServiceConfiguration.class);
    w.put("verification.stackdriver.StackDriverMetricCVConfiguration", StackDriverMetricCVConfiguration.class);
    w.put("verification.VerificationDataAnalysisResponse", VerificationDataAnalysisResponse.class);
    w.put("verification.VerificationStateAnalysisExecutionData", VerificationStateAnalysisExecutionData.class);
    w.put("yaml.errorhandling.GitToHarnessErrorDetails", GitToHarnessErrorDetails.class);
    w.put("yaml.errorhandling.HarnessToGitErrorDetails", HarnessToGitErrorDetails.class);
    w.put("yaml.gitSync.GitFileProcessingSummary", GitFileProcessingSummary.class);
    w.put("yaml.gitSync.GitSyncMetadata", GitSyncMetadata.class);
    w.put("beans.template.ImportedTemplateMetadata", ImportedTemplateMetadata.class);
    w.put("beans.template.CopiedTemplateMetadata", CopiedTemplateMetadata.class);
    w.put("sm.states.customdeployment.InstanceFetchState", InstanceFetchState.class);
    w.put("api.customdeployment.InstanceFetchStateExecutionData", InstanceFetchStateExecutionData.class);
    w.put("api.InstanceFetchStateExecutionSummary", InstanceFetchStateExecutionSummary.class);
    w.put("api.CustomDeploymentTypeInfo", CustomDeploymentTypeInfo.class);
    w.put("api.terraform.TerraformOutputVariables", TerraformOutputVariables.class);
    w.put("api.terragrunt.TerragruntOutputVariables", TerragruntOutputVariables.class);
    w.put("api.arm.ARMOutputVariables", ARMOutputVariables.class);
    MorphiaRegistrarHelperPut sm = (name, clazz) -> w.put("sm.states.spotinst." + name, clazz);

    sm.put("SpotinstDeployExecutionSummary", SpotinstDeployExecutionSummary.class);
    sm.put("SpotInstDeployState", SpotInstDeployState.class);
    sm.put("SpotInstDeployStateExecutionData", SpotInstDeployStateExecutionData.class);
    sm.put("SpotInstListenerUpdateRollbackState", SpotInstListenerUpdateRollbackState.class);
    sm.put("SpotInstListenerUpdateState", SpotInstListenerUpdateState.class);
    sm.put("SpotInstListenerUpdateStateExecutionData", SpotInstListenerUpdateStateExecutionData.class);
    sm.put("SpotInstRollbackState", SpotInstRollbackState.class);
    sm.put("SpotInstServiceSetup", SpotInstServiceSetup.class);
    sm.put("SpotInstSetupExecutionSummary", SpotInstSetupExecutionSummary.class);
    sm.put("SpotInstSetupStateExecutionData", SpotInstSetupStateExecutionData.class);
    sm.put("SpotinstTrafficShiftAlbDeployExecutionData", SpotinstTrafficShiftAlbDeployExecutionData.class);
    sm.put("SpotinstTrafficShiftAlbDeployState", SpotinstTrafficShiftAlbDeployState.class);
    sm.put("SpotinstTrafficShiftAlbRollbackSwitchRoutesState", SpotinstTrafficShiftAlbRollbackSwitchRoutesState.class);
    sm.put("SpotinstTrafficShiftAlbSetupExecutionData", SpotinstTrafficShiftAlbSetupExecutionData.class);
    sm.put("SpotinstTrafficShiftAlbSetupState", SpotinstTrafficShiftAlbSetupState.class);
    sm.put("SpotinstTrafficShiftAlbSwapRoutesExecutionData", SpotinstTrafficShiftAlbSwapRoutesExecutionData.class);
    sm.put("SpotinstTrafficShiftAlbSwitchRoutesState", SpotinstTrafficShiftAlbSwitchRoutesState.class);
  }
}
