package software.wings.security;

/**
 * Created by anubhaw on 3/10/16.
 */

public enum AccessType {
  APP_CREATE,
  APP_READ,
  APP_DELETE,
  PLATFORM_CREATE,
  PLATFORM_READ,
  PLATFORM_DELETE,
  SERVICE_CREATE,
  SERVICE_READ,
  SERVICE_DELETE,
  CONFIG_CREATE,
  CONFIG_READ,
  CONFIG_DELETE,
  ENV_CREATE,
  ENV_READ,
  ENV_DELETE,
  ROLE_CREATE,
  ROLE_READ,
  ROLE_DELETE,
  USER_CREATE,
  USER_READ,
  USER_DELETE,
  HOST_CREATE,
  HOST_READ,
  HOST_DELETE,
  DEPLOYMENT_CREATE,
  DEPLOYMENT_READ,
  DEPLOYMENT_DELETE,
  RELEASE_CREATE,
  RELEASE_READ,
  RELEASE_DELETE,
  DELIVERY_CREATE,
  DELIVERY_READ,
  DELIVERY_DELETE,
  ARTIFACTS_CREATE,
  ARTIFACTS_READ,
  ARTIFACTS_DELETE;
}
