# to be used when building
FROM harness/alpine:safe-alpine3.12-sec1338

# Add the capsule JAR and config.yml
COPY delegate-service-capsule.jar keystore.jks delegate-service-config.yml redisson-jcache.yaml alpn-boot-8.1.13.v20181017.jar /opt/harness/

RUN wget https://github.com/mikefarah/yq/releases/download/3.3.2/yq_linux_amd64 -O /usr/bin/yq -O /usr/bin/yq
RUN chmod +x /usr/bin/yq

COPY scripts /opt/harness

RUN set -x \
# create required files and directories
    && mkdir /opt/harness/plugins \
    && mkdir /opt/harness/logs \
# forward manager logs to docker log collector
    && ln -sfT /dev/stdout /opt/harness/logs/delegate-service.log \
# setup user and file permissions
    && addgroup -S 65534 && adduser -S 65534 -G 65534 \
    && chown -R 65534:65534 /opt/harness/ /tmp \
    && chmod 700 -R /opt/harness/ \
    && chmod 700 -R /tmp

USER 65534

WORKDIR /opt/harness

CMD [ "./run.sh" ]
