-- Copyright 2023 Harness Inc. All rights reserved.
-- Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
-- that can be found in the licenses directory at the root of this repository, also available at
-- https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

---------- NG_INSTANCE_STATS_ITERATOR TABLE START ------------
BEGIN;
CREATE TABLE IF NOT EXISTS NG_INSTANCE_STATS_ITERATOR (
	REPORTEDAT TIMESTAMPTZ NOT NULL,
	ACCOUNTID TEXT,
	ORGID TEXT,
	PROJECTID TEXT,
	SERVICEID TEXT
);

CREATE INDEX IF NOT EXISTS NG_INSTANCE_STATS_ITERATOR_ACCOUNTID_INDEX ON NG_INSTANCE_STATS_ITERATOR(ACCOUNTID,REPORTEDAT DESC);
CREATE INDEX IF NOT EXISTS NG_INSTANCE_STATS_ITERATOR_ORGID_INDEX ON NG_INSTANCE_STATS_ITERATOR(ORGID,REPORTEDAT DESC);
CREATE INDEX IF NOT EXISTS NG_INSTANCE_STATS_ITERATOR_PROJECTID_INDEX ON NG_INSTANCE_STATS_ITERATOR(PROJECTID,REPORTEDAT DESC);
CREATE INDEX IF NOT EXISTS NG_INSTANCE_STATS_ITERATOR_SERVICEID_INDEX ON NG_INSTANCE_STATS_ITERATOR(SERVICEID,REPORTEDAT DESC);
CREATE UNIQUE INDEX IF NOT EXISTS NG_INSTANCE_STATS_ITERATOR_ACCOUNTID_ORGID_PROJECTID_UNIQUE_INDEX ON NG_INSTANCE_STATS_ITERATOR(ACCOUNTID, ORGID, PROJECTID,SERVICEID);

COMMIT;

---------- NG_INSTANCE_STATS_ITERATOR TABLE END ------------
