FROM us.gcr.io/platform-205701/alpine:safe-alpine3.12-sec1096-apm
WORKDIR /code
RUN apk add --no-cache python3 py3-pip
RUN apk add --no-cache gcc musl-dev linux-headers redis
COPY requirements.txt .
RUN pip3 install -r requirements.txt
COPY . .
RUN chmod +x run.sh

ENTRYPOINT [ "sh", "./run.sh" ]
