package io.harness.enforcement.constants;

/**
 * Please register all feature names here.
 */
public enum FeatureRestrictionName {
  // Test purpose
  TEST1,
  TEST2,
  TEST3,
  TEST4,
  TEST5,

  // CCM Features
  PERSPECTIVES,
  CCM_K8S_CLUSTERS,

  // All Features
  MULTIPLE_ORGANIZATIONS,
  MULTIPLE_PROJECTS,
  INTEGRATED_APPROVALS_WITH_HARNESS_UI,
  INTEGRATED_APPROVALS_WITH_JIRA,
  SECRET_MANAGERS,
  DEPLOYMENTS,
  SERVICES,
  BUILDS,
  SAML_SUPPORT,
  OAUTH_SUPPORT,
  LDAP_SUPPORT,
  TWO_FACTOR_AUTH_SUPPORT,
  CUSTOM_ROLES,
  CUSTOM_RESOURCE_GROUPS,

  // CD Step Palette
  K8S_BG_SWAP_SERVICES,
  K8S_BLUE_GREEN_DEPLOY,
  K8S_APPLY,
  K8S_DELETE,
  K8S_CANARY_DELETE,
  K8S_ROLLING_DEPLOY,
  K8S_CANARY_DEPLOY,
  K8S_SCALE,
  K8S_ROLLING_ROLLBACK,
  TERRAFORM_APPLY,
  TERRAFORM_PLAN,
  TERRAFORM_DESTROY,
  TERRAFORM_ROLLBACK;
}
