# Copyright 2022 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

# To be used when building in CIE

FROM us.gcr.io/platform-205701/ubi/ubi-java:latest
USER root
# Add the capsule JAR and other files
COPY --chown=65534:65534 eventsapi-monitor-capsule.jar /opt/harness/
COPY --chown=65534:65534 config.yml /opt/harness/
COPY --chown=65534:65534 redislabs_ca.pem /opt/harness/
COPY --chown=65534:65534 install_redis.sh /opt/harness/
COPY --chown=65534:65534 protocol.info /opt/harness/

RUN yum install -y gcc gcc-c++ openssl wget openssl-devel

RUN chmod +x /opt/harness/install_redis.sh && sh /opt/harness/install_redis.sh

COPY --chown=65534:65534 scripts /opt/harness

RUN chmod +x /opt/harness/*.sh && chmod 700 -R /opt/harness/ && chown -R 65534:65534 /opt/harness/

WORKDIR /opt/harness

CMD [ "./run.sh" ]

USER 65534