FROM toli/harness-learning-engine:latest

COPY requirements-test.txt /home/harness/
COPY tests /home/harness/tests
WORKDIR /home/harness/

RUN make clean && pip install -r requirements-test.txt && \
    sed -i s/"; deactivate"// Makefile

# can run the image from Mac  and then run 'make tests' in a container and develop locally
# to build: docker build -t toli/harness-learning-engine:dev .
# to test in jenkins: docker run --rm toli/harness-learning-engine:dev make test
# to develop locally with mounted local dir into the container:
#   docker run --rm -it -v `pwd`:/home/harness toli/harness-learning-engine:dev bash