package io.harness.delegate.beans.ci.pod;

public enum EnvVariableEnum {
  DOCKER_USERNAME,
  DOCKER_PASSWORD,
  DOCKER_REGISTRY,
  AWS_ACCESS_KEY,
  AWS_SECRET_KEY,
  GCP_KEY,
  GCP_KEY_AS_FILE,
  ARTIFACTORY_USERNAME,
  ARTIFACTORY_PASSWORD,
  ARTIFACTORY_ENDPOINT
}
