# CIE AGENT - DOCKER BUILD

# Usage: Used to run docker build for applications
# Test image locally by running this command:
#
# $ docker build \
#     -f Dockerfile-docker-build-cie-agent" \
#     -t <tag> \
#     .

FROM us.gcr.io/platform-205701/ubi/cie-agents/java-go-cie-agent:latest

USER root

RUN yum install -y yum-utils
RUN yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo \
    && yum install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin