# Copyright 2022 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

# to be used when building in Jenkins
FROM us.gcr.io/platform-205701/ubi/ubi-java:latest as base

# Add the capsule JAR and config.yml
COPY --chown=65534:65534 migrator-capsule.jar /opt/harness/
COPY --chown=65534:65534 newrelic.yml /opt/harness/
COPY --chown=65534:65534 keystore.jks  /opt/harness/
COPY --chown=65534:65534 config.yml /opt/harness/
COPY --chown=65534:65534 hazelcast.xml /opt/harness/
COPY --chown=65534:65534 redisson-jcache.yaml /opt/harness/
COPY --chown=65534:65534 protocol.info /opt/harness/

COPY --chown=65534:65534 scripts /opt/harness

USER root
RUN microdnf install -y dnf yum
RUN yum -y install fontconfig dejavu-sans-fonts wget
RUN wget https://github.com/mikefarah/yq/releases/download/v4.27.5/yq_linux_amd64 -O /usr/bin/yq -O /usr/bin/yq
RUN chmod +x /usr/bin/yq

RUN chmod +x /opt/harness/*.sh

WORKDIR /opt/harness

CMD [ "./run.sh" ]
