# to be used when building in Jenkins
FROM us.gcr.io/platform-205701/harness/serverjre_8:232

# Add the capsule JAR and config.yml
COPY migrator-capsule.jar keystore.jks /opt/harness/

RUN chmod +x /opt/harness/*.sh
RUN mkdir /opt/harness/plugins

WORKDIR /opt/harness

CMD [ "./run.sh" ]
