-- Copyright 2020 Harness Inc. All rights reserved.
-- Use of this source code is governed by the PolyForm Shield 1.0.0 license
-- that can be found in the licenses directory at the root of this repository, also available at
-- https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.

BEGIN;

ALTER TABLE CV_CONFIGURATIONS ADD COLUMN IF NOT EXISTS LICENSE_TYPE VARCHAR(20);
ALTER TABLE CV_CONFIGURATIONS ADD COLUMN IF NOT EXISTS ACCOUNT_NAME TEXT;
ALTER TABLE CV_CONFIGURATIONS ADD COLUMN IF NOT EXISTS ENVIRONMENT_TYPE VARCHAR(20);
ALTER TABLE CV_CONFIGURATIONS ADD COLUMN IF NOT EXISTS ENABLED BOOLEAN;
ALTER TABLE CV_CONFIGURATIONS ADD COLUMN IF NOT EXISTS LAST_EXECUTION_TIME TIMESTAMP;
ALTER TABLE CV_CONFIGURATIONS ADD COLUMN IF NOT EXISTS HAS_DATA BOOLEAN;

COMMIT;

BEGIN;

CREATE INDEX IF NOT EXISTS CC_LICENSE_TYPE_INDEX ON CV_CONFIGURATIONS(LICENSE_TYPE, CREATION_TIME DESC);
CREATE INDEX IF NOT EXISTS VWS_ACCOUNT_NAME_INDEX ON CV_CONFIGURATIONS(ACCOUNT_NAME, CREATION_TIME DESC);
CREATE INDEX IF NOT EXISTS VWS_ENVIRONMENT_TYPE_INDEX ON CV_CONFIGURATIONS(ENVIRONMENT_TYPE, CREATION_TIME DESC);
CREATE INDEX IF NOT EXISTS VWS_ENABLED_INDEX ON CV_CONFIGURATIONS(ENABLED, CREATION_TIME DESC);
CREATE INDEX IF NOT EXISTS VWS_LAST_EXECUTION_TIMEE_INDEX ON CV_CONFIGURATIONS(LAST_EXECUTION_TIME, CREATION_TIME DESC);
CREATE INDEX IF NOT EXISTS VWS_HAS_DATA_TYPE_INDEX ON CV_CONFIGURATIONS(HAS_DATA, CREATION_TIME DESC);

COMMIT;
