-- Copyright 2020 Harness Inc. All rights reserved.
-- Use of this source code is governed by the PolyForm Shield 1.0.0 license
-- that can be found in the licenses directory at the root of this repository, also available at
-- https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.

BEGIN;
ALTER TABLE DEPLOYMENT ADD COLUMN IF NOT EXISTS PARENT_PIPELINE_ID TEXT;
ALTER TABLE DEPLOYMENT_STAGE ADD COLUMN IF NOT EXISTS PARENT_PIPELINE_ID TEXT;
ALTER TABLE DEPLOYMENT_PARENT ADD COLUMN IF NOT EXISTS PARENT_PIPELINE_ID TEXT;
ALTER TABLE DEPLOYMENT ADD COLUMN IF NOT EXISTS CREATED_BY_TYPE TEXT;
ALTER TABLE DEPLOYMENT_STAGE ADD COLUMN IF NOT EXISTS CREATED_BY_TYPE TEXT;
ALTER TABLE DEPLOYMENT_PARENT ADD COLUMN IF NOT EXISTS CREATED_BY_TYPE TEXT;
COMMIT ;