-- Copyright 2020 Harness Inc. All rights reserved.
-- Use of this source code is governed by the PolyForm Shield 1.0.0 license
-- that can be found in the licenses directory at the root of this repository, also available at
-- https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.

---------- CONFIGURATION TABLE START -----------
BEGIN;
CREATE TABLE IF NOT EXISTS CV_CONFIGURATIONS (
    CONFIGID TEXT NOT NULL,
	CREATIONTIME TIMESTAMP NOT NULL,
	ACCOUNTID TEXT NOT NULL,
	SERVICEID TEXT NOT NULL,
	VERIFICATIONPROVIDERTYPE TEXT NOT NULL,
	ANALYSISTOLERANCE TEXT NOT NULL,
	ALERTSETUP BOOLEAN NOT NULL,
	ALERTTHRESHOLD FLOAT,
	PRIMARY KEY (CONFIGID, CREATIONTIME)
);
COMMIT;


SELECT CREATE_HYPERTABLE('CV_CONFIGURATIONS','creationtime');
BEGIN;
CREATE INDEX IF NOT EXISTS CV_CONFIGURATIONS_ACCOUNTID_INDEX ON CV_CONFIGURATIONS(ACCOUNTID,CREATIONTIME DESC);
COMMIT;
