BEGIN;

ALTER TABLE ANOMALIES ADD COLUMN IF NOT EXISTS SLACKDAILYNOTIFICATION BOOLEAN DEFAULT FALSE;
ALTER TABLE ANOMALIES ADD COLUMN IF NOT EXISTS SLACKINSTANTNOTIFICATION BOOLEAN DEFAULT FALSE;
ALTER TABLE ANOMALIES ADD COLUMN IF NOT EXISTS SLACKWEEKLYNOTIFICATION BOOLEAN DEFAULT FALSE;

COMMIT;