-- Copyright 2022 Harness Inc. All rights reserved.
-- Use of this source code is governed by the PolyForm Shield 1.0.0 license
-- that can be found in the licenses directory at the root of this repository, also available at
-- https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.

BEGIN;
ALTER TABLE CG_APPLICATIONS ADD COLUMN IF NOT EXISTS IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE CG_CLOUD_PROVIDERS ADD COLUMN IF NOT EXISTS IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE CG_ENVIRONMENTS ADD COLUMN IF NOT EXISTS IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE CG_INFRA_DEFINITION ADD COLUMN IF NOT EXISTS IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE CG_PIPELINES ADD COLUMN IF NOT EXISTS IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE CG_SERVICES ADD COLUMN IF NOT EXISTS IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE CG_TAGS ADD COLUMN IF NOT EXISTS IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE CG_USERS ADD COLUMN IF NOT EXISTS IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE CG_WORKFLOWS ADD COLUMN IF NOT EXISTS IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS IS_DELETED_APPLICATIONS_INDEX ON CG_APPLICATIONS(is_deleted);
CREATE INDEX IF NOT EXISTS IS_DELETED_CLOUD_PROVIDERS_INDEX ON CG_CLOUD_PROVIDERS(is_deleted);
CREATE INDEX IF NOT EXISTS IS_DELETED_ENVIRONMENTS_INDEX ON CG_ENVIRONMENTS(is_deleted);
CREATE INDEX IF NOT EXISTS IS_DELETED_INFRA_DEFINITION_INDEX ON CG_INFRA_DEFINITION(is_deleted);
CREATE INDEX IF NOT EXISTS IS_DELETED_PIPELINES_INDEX ON CG_PIPELINES(is_deleted);
CREATE INDEX IF NOT EXISTS IS_DELETED_SERVICES_INDEX ON CG_SERVICES(is_deleted);
CREATE INDEX IF NOT EXISTS IS_DELETED_TAGS_INDEX ON CG_TAGS(is_deleted);
CREATE INDEX IF NOT EXISTS IS_DELETED_USERS_INDEX ON CG_USERS(is_deleted);
CREATE INDEX IF NOT EXISTS IS_DELETED_WORKFLOWS_INDEX ON CG_WORKFLOWS(is_deleted);
COMMIT ;