-- Copyright 2020 Harness Inc. All rights reserved.
-- Use of this source code is governed by the PolyForm Shield 1.0.0 license
-- that can be found in the licenses directory at the root of this repository, also available at
-- https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.

BEGIN;
CREATE INDEX IF NOT EXISTS BILLING_DATA_HOURLY_WORKLOADNAME_WITHOUT_CLUSTER_INDEX ON BILLING_DATA_HOURLY(ACCOUNTID, WORKLOADNAME, STARTTIME DESC);
CREATE INDEX IF NOT EXISTS BILLING_DATA_HOURLY_NAMESPACE_WITHOUT_CLUSTER_INDEX ON BILLING_DATA_HOURLY(ACCOUNTID, NAMESPACE, STARTTIME DESC);
CREATE INDEX IF NOT EXISTS BILLING_DATA_WORKLOADNAME_WITHOUT_CLUSTER_INDEX ON BILLING_DATA(ACCOUNTID, WORKLOADNAME, STARTTIME DESC);
CREATE INDEX IF NOT EXISTS BILLING_DATA_NAMESPACE_WITHOUT_CLUSTER_INDEX ON BILLING_DATA(ACCOUNTID, NAMESPACE, STARTTIME DESC);
COMMIT;
