BEGIN;
ALTER TABLE BUDGET_ALERTS ADD COLUMN ALERTBASEDON TEXT NOT NULL DEFAULT 'ACTUAL_COST';
UPDATE BUDGET_ALERTS SET ALERTBASEDON = 'FORECASTED_COST' WHERE ACTUALCOST < BUDGETEDCOST*ALERTTHRESHOLD/100;
COMMIT;