-- Copyright 2020 Harness Inc. All rights reserved.
-- Use of this source code is governed by the PolyForm Shield 1.0.0 license
-- that can be found in the licenses directory at the root of this repository, also available at
-- https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.

BEGIN;

ALTER TABLE VERIFICATION_WORKFLOW_STATS ADD COLUMN IF NOT EXISTS LICENSE_TYPE VARCHAR(20);
ALTER TABLE VERIFICATION_WORKFLOW_STATS ADD COLUMN IF NOT EXISTS ACCOUNT_NAME TEXT;

COMMIT;

BEGIN;

CREATE INDEX IF NOT EXISTS VWS_LICENSE_TYPE_INDEX ON VERIFICATION_WORKFLOW_STATS(LICENSE_TYPE, END_TIME DESC);
CREATE INDEX IF NOT EXISTS VWS_ACCOUNT_NAME_INDEX ON VERIFICATION_WORKFLOW_STATS(ACCOUNT_NAME, END_TIME DESC);

COMMIT;
