-- Copyright 2020 Harness Inc. All rights reserved.
-- Use of this source code is governed by the PolyForm Shield 1.0.0 license
-- that can be found in the licenses directory at the root of this repository, also available at
-- https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.

BEGIN;
CREATE TABLE IF NOT EXISTS COST_EVENT_DATA (
	STARTTIME TIMESTAMPTZ NOT NULL,
	ACCOUNTID TEXT NOT NULL,
	SETTINGID TEXT,
	CLUSTERID TEXT,
	CLUSTERTYPE TEXT,
	INSTANCEID TEXT,
	INSTANCETYPE TEXT,
	APPID TEXT,
	SERVICEID TEXT,
	ENVID TEXT,
	CLOUDPROVIDERID TEXT,
	DEPLOYMENTID TEXT,
	CLOUDPROVIDER TEXT,
	EVENTDESCRIPTION TEXT,
	COSTEVENTTYPE TEXT,
	COSTEVENTSOURCE TEXT,
	NAMESPACE TEXT,
	WORKLOADNAME TEXT,
	WORKLOADTYPE TEXT,
	CLOUDSERVICENAME TEXT,
	TASKID TEXT,
	LAUNCHTYPE TEXT,
	BILLINGAMOUNT DOUBLE PRECISION,
	OLDYAMLREF TEXT,
	NEWYAMLREF TEXT
);
COMMIT;

SELECT CREATE_HYPERTABLE('COST_EVENT_DATA','starttime',if_not_exists => TRUE);
