---------- KUBERNETES_UTILIZATION_DATA TABLE START ------------
BEGIN;
CREATE TABLE IF NOT EXISTS KUBERNETES_UTILIZATION_DATA (
	STARTTIME TIMESTAMPTZ NOT NULL,
	ENDTIME TIMESTAMPTZ NOT NULL,
	ACCOUNTID TEXT NOT NULL,
	SETTINGID TEXT NOT NULL,
	INSTANCEID TEXT NOT NULL,
	INSTANCETYPE TEXT NOT NULL,
	CPU DOUBLE PRECISION  NOT NULL,
	MEMORY DOUBLE PRECISION  NOT NULL
);
COMMIT;
SELECT CREATE_HYPERTABLE('KUBERNETES_UTILIZATION_DATA','starttime',if_not_exists => TRUE);

BEGIN;
CREATE INDEX IF NOT EXISTS KUBERNETES_UTILIZATION_DATA_INSTANCEID_INDEX ON KUBERNETES_UTILIZATION_DATA(INSTANCEID, STARTTIME DESC);
COMMIT;
---------- KUBERNETES_UTILIZATION_DATA TABLE END ------------