-- Copyright 2020 Harness Inc. All rights reserved.
-- Use of this source code is governed by the PolyForm Shield 1.0.0 license
-- that can be found in the licenses directory at the root of this repository, also available at
-- https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.

---------- BILLING_DATA TABLE START ------------
BEGIN;
CREATE TABLE IF NOT EXISTS BILLING_DATA_HOURLY (
	STARTTIME TIMESTAMPTZ NOT NULL,
	ENDTIME TIMESTAMPTZ NOT NULL,
	ACCOUNTID TEXT NOT NULL,
	SETTINGID TEXT,
	INSTANCEID TEXT NOT NULL,
	INSTANCETYPE TEXT NOT NULL,
	BILLINGACCOUNTID TEXT,
	CLUSTERID TEXT,
	CLUSTERNAME TEXT,
	APPID TEXT,
	SERVICEID TEXT,
	ENVID TEXT,
	CLOUDPROVIDERID TEXT,
	PARENTINSTANCEID TEXT,
	REGION TEXT,
	LAUNCHTYPE TEXT,
	CLUSTERTYPE TEXT,
	WORKLOADNAME TEXT,
	WORKLOADTYPE TEXT,
	NAMESPACE TEXT,
	CLOUDSERVICENAME TEXT,
	TASKID TEXT,
	CLOUDPROVIDER TEXT,
	BILLINGAMOUNT DOUBLE PRECISION  NOT NULL,
	CPUBILLINGAMOUNT DOUBLE PRECISION,
	MEMORYBILLINGAMOUNT DOUBLE PRECISION,
	IDLECOST DOUBLE PRECISION,
	CPUIDLECOST DOUBLE PRECISION,
	MEMORYIDLECOST DOUBLE PRECISION,
	USAGEDURATIONSECONDS DOUBLE PRECISION,
	CPUUNITSECONDS DOUBLE PRECISION,
	MEMORYMBSECONDS DOUBLE PRECISION,
	MAXCPUUTILIZATION DOUBLE PRECISION,
	MAXMEMORYUTILIZATION DOUBLE PRECISION,
	AVGCPUUTILIZATION DOUBLE PRECISION,
	AVGMEMORYUTILIZATION DOUBLE PRECISION,
	SYSTEMCOST DOUBLE PRECISION,
	CPUSYSTEMCOST DOUBLE PRECISION,
	MEMORYSYSTEMCOST DOUBLE PRECISION,
	ACTUALIDLECOST DOUBLE PRECISION,
	CPUACTUALIDLECOST DOUBLE PRECISION,
 	MEMORYACTUALIDLECOST DOUBLE PRECISION,
 	UNALLOCATEDCOST DOUBLE PRECISION,
	CPUUNALLOCATEDCOST DOUBLE PRECISION,
	MEMORYUNALLOCATEDCOST DOUBLE PRECISION,
	INSTANCENAME TEXT
);
COMMIT;
SELECT CREATE_HYPERTABLE('BILLING_DATA_HOURLY','starttime',if_not_exists => TRUE);

BEGIN;
CREATE INDEX IF NOT EXISTS BILLING_DATA_HOURLY_ACCOUNTID_INDEX ON BILLING_DATA_HOURLY(ACCOUNTID, STARTTIME DESC);
CREATE INDEX IF NOT EXISTS BILLING_DATA_HOURLY_APPID_COMPOSITE_INDEX ON BILLING_DATA_HOURLY(ACCOUNTID, APPID,STARTTIME DESC);
CREATE INDEX IF NOT EXISTS BILLING_DATA_HOURLY_WORKLOADNAME_COMPOSITE_INDEX ON BILLING_DATA_HOURLY(ACCOUNTID, CLUSTERID, WORKLOADNAME, STARTTIME DESC);
CREATE INDEX IF NOT EXISTS BILLING_DATA_HOURLY_NAMESPACE_COMPOSITE_INDEX ON BILLING_DATA_HOURLY(ACCOUNTID, CLUSTERID, NAMESPACE, STARTTIME DESC);
CREATE INDEX IF NOT EXISTS BILLING_DATA_HOURLY_TASKID_COMPOSITE_INDEX ON BILLING_DATA_HOURLY(ACCOUNTID, CLUSTERID, TASKID, STARTTIME DESC);
CREATE INDEX IF NOT EXISTS BILLING_DATA_HOURLY_CLOUDSERVICENAME_COMPOSITE_INDEX ON BILLING_DATA_HOURLY(ACCOUNTID, CLUSTERID, CLOUDSERVICENAME, STARTTIME DESC);
CREATE INDEX IF NOT EXISTS BILLING_DATA_HOURLY_LAUNCHTYPE_COMPOSITE_INDEX ON BILLING_DATA_HOURLY(ACCOUNTID, CLUSTERID, LAUNCHTYPE, STARTTIME DESC);
CREATE INDEX IF NOT EXISTS BILLING_DATA_HOURLY_CLUSTERID_COMPOSITE_INDEX ON BILLING_DATA_HOURLY(ACCOUNTID, CLUSTERID, STARTTIME DESC);
CREATE INDEX IF NOT EXISTS BILLING_DATA_HOURLY_CLOUDPROVIDERID_COMPOSITE_INDEX ON BILLING_DATA_HOURLY(ACCOUNTID, CLOUDPROVIDERID, STARTTIME DESC);
CREATE UNIQUE INDEX IF NOT EXISTS BILLING_DATA_HOURLY_UNIQUE_INDEX ON BILLING_DATA_HOURLY(ACCOUNTID, SETTINGID, CLUSTERID, INSTANCEID, INSTANCETYPE, STARTTIME DESC);
COMMIT;
---------- BILLING_DATA TABLE END ------------
