-- Copyright 2021 Harness Inc. All rights reserved.
-- Use of this source code is governed by the PolyForm Shield 1.0.0 license
-- that can be found in the licenses directory at the root of this repository, also available at
-- https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.

---------- DEPLOYMENT_STAGE TABLE START ------------
BEGIN;
CREATE TABLE IF NOT EXISTS DEPLOYMENT_STAGE (
    EXECUTIONID TEXT NOT NULL,
    STARTTIME TIMESTAMPTZ NOT NULL,
    ENDTIME TIMESTAMPTZ NOT NULL,
    ACCOUNTID TEXT NOT NULL,
    APPID TEXT NOT NULL,
    TRIGGERED_BY TEXT,
    TRIGGER_ID TEXT,
    STATUS VARCHAR(20),
    SERVICES TEXT[],
    WORKFLOWS TEXT[],
    CLOUDPROVIDERS TEXT[],
    ENVIRONMENTS TEXT[],
    PIPELINE TEXT,
    DURATION BIGINT NOT NULL,
    ARTIFACTS TEXT[],
    ENVTYPES TEXT[],
    PARENT_EXECUTION TEXT,
    STAGENAME TEXT,
    ROLLBACK_DURATION BIGINT,
    INSTANCES_DEPLOYED INT,
    TAGS HSTORE,

    PRIMARY KEY(EXECUTIONID, ENDTIME)
)
WITH (
    OIDS = FALSE
);
COMMIT;

SELECT CREATE_HYPERTABLE('DEPLOYMENT_STAGE','endtime',chunk_time_interval => interval '3 month',if_not_exists => TRUE);

BEGIN;
CREATE INDEX IF NOT EXISTS DEPLOYMENT_STAGE_TRIGGERED_BY_INDEX ON DEPLOYMENT_STAGE(TRIGGERED_BY,ENDTIME DESC);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_STAGE_TRIGGER_ID_INDEX ON DEPLOYMENT_STAGE(TRIGGER_ID,ENDTIME DESC);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_STAGE_APPID_INDEX ON DEPLOYMENT_STAGE(APPID,ENDTIME DESC);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_STAGE_ACCOUNTID_INDEX ON DEPLOYMENT_STAGE(ACCOUNTID,ENDTIME DESC);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_STAGE_PIPELINE_INDEX ON DEPLOYMENT_STAGE(PIPELINE,ENDTIME DESC);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_STAGE_STATUS_INDEX ON DEPLOYMENT_STAGE(STATUS,ENDTIME DESC);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_STAGE_STARTTIME_INDEX ON DEPLOYMENT_STAGE(STARTTIME,ENDTIME DESC);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_STAGE_DURATION_INDEX ON DEPLOYMENT_STAGE(DURATION,ENDTIME DESC);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_STAGE_SERVICES_GIN_INDEX ON DEPLOYMENT_STAGE USING GIN(SERVICES);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_STAGE_WORKFLOWS_GIN_INDEX ON DEPLOYMENT_STAGE USING GIN(WORKFLOWS);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_STAGE_ARTIFACTS_GIN_INDEX ON DEPLOYMENT_STAGE USING GIN(ARTIFACTS);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_STAGE_CLOUDPROVIDERS_GIN_INDEX ON DEPLOYMENT_STAGE USING GIN(CLOUDPROVIDERS);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_STAGE_ENVIRONMENTS_GIN_INDEX ON DEPLOYMENT_STAGE USING GIN(ENVIRONMENTS);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_STAGE_TAGS_GIN_INDEX ON DEPLOYMENT_STAGE USING GIN(TAGS);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_STAGE_ACCOUNTID_STATUS_INDEX ON DEPLOYMENT_STAGE(ACCOUNTID,STATUS);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_STAGE_ENV_TYPE_INDEX ON DEPLOYMENT_STAGE(ENVTYPES,ENDTIME DESC);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_STAGE_PARENT_EXECUTION_INDEX ON DEPLOYMENT_STAGE(PARENT_EXECUTION,ENDTIME DESC);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_STAGE_STAGENAME_INDEX ON DEPLOYMENT_STAGE(STAGENAME,ENDTIME DESC);
COMMIT;

---------- DEPLOYMENT_STAGE TABLE END ------------
