BEGIN;

DELETE FROM ANOMALIES where ID IN (select  ID from anomalies group by ID, ANOMALYTIME having count(*) > 1);

COMMIT;


BEGIN;

CREATE UNIQUE INDEX IF NOT EXISTS ANOMALIES_PKEY ON ANOMALIES (ID, ANOMALYTIME);

COMMIT;