-- Copyright 2021 Harness Inc. All rights reserved.
-- Use of this source code is governed by the PolyForm Shield 1.0.0 license
-- that can be found in the licenses directory at the root of this repository, also available at
-- https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.

---------- INSTANCE_STATS_DAY TABLE START ------------
BEGIN;
CREATE TABLE IF NOT EXISTS INSTANCE_STATS_DAY (
	REPORTEDAT TIMESTAMPTZ NOT NULL,
	ACCOUNTID TEXT,
	APPID TEXT,
	SERVICEID TEXT,
	ENVID TEXT,
	CLOUDPROVIDERID TEXT,
	INSTANCETYPE TEXT,
	INSTANCECOUNT INTEGER,
	ARTIFACTID TEXT,
	WEEKTIMESTAMP TIMESTAMP NOT NULL,
	MONTHTIMESTAMP TIMESTAMP NOT NULL,
	SANITYSTATUS BOOLEAN NOT NULL DEFAULT FALSE,
	CREATEDAT TIMESTAMPTZ DEFAULT (NOW()),
    UPDATEDAT TIMESTAMPTZ DEFAULT (NOW()),

	CONSTRAINT INSTANCE_STATS_DAY_UNIQUE_RECORD_INDEX UNIQUE(ACCOUNTID,APPID,SERVICEID,ENVID,CLOUDPROVIDERID,INSTANCETYPE,REPORTEDAT)
);
COMMIT;

SELECT CREATE_HYPERTABLE('INSTANCE_STATS_DAY','reportedat',chunk_time_interval => interval '3 month',if_not_exists => TRUE);

BEGIN;
CREATE INDEX IF NOT EXISTS INSTANCE_STATS_DAY_APPID_INDEX ON INSTANCE_STATS_DAY(APPID,REPORTEDAT DESC);
CREATE INDEX IF NOT EXISTS INSTANCE_STATS_DAY_ACCOUNTID_INDEX ON INSTANCE_STATS_DAY(ACCOUNTID,REPORTEDAT DESC);
CREATE INDEX IF NOT EXISTS INSTANCE_STATS_DAY_SERVICEID_INDEX ON INSTANCE_STATS_DAY(SERVICEID,REPORTEDAT DESC);
CREATE INDEX IF NOT EXISTS INSTANCE_STATS_DAY_ENVID_INDEX ON INSTANCE_STATS_DAY(ENVID,REPORTEDAT DESC);
CREATE INDEX IF NOT EXISTS INSTANCE_STATS_DAY_CLOUDPROVIDERID_INDEX ON INSTANCE_STATS_DAY(CLOUDPROVIDERID,REPORTEDAT DESC);
CREATE INDEX IF NOT EXISTS INSTANCE_STATS_DAY_INSTANCECOUNT_INDEX ON INSTANCE_STATS_DAY(INSTANCECOUNT,REPORTEDAT DESC);
CREATE INDEX IF NOT EXISTS INSTANCE_STATS_DAY_ARTIFACTID_INDEX ON INSTANCE_STATS_DAY(ARTIFACTID,REPORTEDAT DESC);
CREATE INDEX IF NOT EXISTS INSTANCE_STATS_DAY_CREATEDAT_INDEX ON INSTANCE_STATS_DAY(CREATEDAT DESC);
CREATE INDEX IF NOT EXISTS INSTANCE_STATS_DAY_UPDATEDAT_INDEX ON INSTANCE_STATS_DAY(UPDATEDAT DESC);
CREATE INDEX IF NOT EXISTS INSTANCE_STATS_DAY_UPDATEDAT_INDEX ON INSTANCE_STATS_DAY(WEEKTIMESTAMP DESC, REPORTEDAT DESC);
CREATE INDEX IF NOT EXISTS INSTANCE_STATS_DAY_UPDATEDAT_INDEX ON INSTANCE_STATS_DAY(MONTHTIMESTAMP DESC, REPORTEDAT DESC);
CREATE INDEX IF NOT EXISTS INSTANCE_STATS_DAY_SANITYSTATUS_INDEX ON INSTANCE_STATS_DAY(SANITYSTATUS,REPORTEDAT DESC);
COMMIT;

DROP TRIGGER IF EXISTS update_updatedAt_col ON INSTANCE_STATS_DAY;
CREATE TRIGGER update_updatedAt_col BEFORE UPDATE ON INSTANCE_STATS_DAY FOR EACH ROW EXECUTE PROCEDURE update_updatedAt_column();

---------- INSTANCE_STATS_DAY TABLE END ------------
