-- Copyright 2020 Harness Inc. All rights reserved.
-- Use of this source code is governed by the PolyForm Shield 1.0.0 license
-- that can be found in the licenses directory at the root of this repository, also available at
-- https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.

---------- INSTANCE TABLE START ------------
BEGIN;
CREATE TABLE IF NOT EXISTS INSTANCE (
	CREATEDAT TIMESTAMPTZ NOT NULL,
	DELETEDAT TIMESTAMPTZ,
	ISDELETED BOOLEAN DEFAULT FALSE,
	INSTANCEID TEXT NOT NULL,
	ACCOUNTID TEXT NOT NULL,
	APPID TEXT,
	SERVICEID TEXT,
	ENVID TEXT,
	CLOUDPROVIDERID TEXT,
	INSTANCETYPE TEXT,
	ARTIFACTID TEXT
);
COMMIT;
SELECT CREATE_HYPERTABLE('INSTANCE','createdat',if_not_exists => TRUE);

BEGIN;
CREATE INDEX IF NOT EXISTS INSTANCE_APPID_INDEX ON INSTANCE(APPID,CREATEDAT DESC);
CREATE INDEX IF NOT EXISTS INSTANCE_ACCOUNTID_INDEX ON INSTANCE(ACCOUNTID,CREATEDAT DESC);
CREATE INDEX IF NOT EXISTS INSTANCE_SERVICEID_INDEX ON INSTANCE(SERVICEID,CREATEDAT DESC);
CREATE INDEX IF NOT EXISTS INSTANCE_ENVID_INDEX ON INSTANCE(ENVID,CREATEDAT DESC);
CREATE INDEX IF NOT EXISTS INSTANCE_CLOUDPROVIDERID_INDEX ON INSTANCE(CLOUDPROVIDERID,CREATEDAT DESC);
CREATE INDEX IF NOT EXISTS INSTANCE_ARTIFACTID_INDEX ON INSTANCE(ARTIFACTID,CREATEDAT DESC);
COMMIT;
---------- INSTANCE TABLE END ------------
