-- Copyright 2021 Harness Inc. All rights reserved.
-- Use of this source code is governed by the PolyForm Shield 1.0.0 license
-- that can be found in the licenses directory at the root of this repository, also available at
-- https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.

---------- DEPLOYMENT_PARENT TABLE START ------------
BEGIN;
CREATE TABLE IF NOT EXISTS DEPLOYMENT_PARENT (
    EXECUTIONID TEXT NOT NULL,
    STARTTIME TIMESTAMPTZ NOT NULL,
    ENDTIME TIMESTAMPTZ NOT NULL,
    ACCOUNTID TEXT NOT NULL,
    APPID TEXT NOT NULL,
    TRIGGERED_BY TEXT,
    TRIGGER_ID TEXT,
    STATUS VARCHAR(20),
    SERVICES TEXT[],
    WORKFLOWS TEXT[],
    CLOUDPROVIDERS TEXT[],
    ENVIRONMENTS TEXT[],
    PIPELINE TEXT,
    DURATION BIGINT NOT NULL,
    ARTIFACTS TEXT[],
    ENVTYPES TEXT[],
    PARENT_EXECUTION TEXT,
    STAGENAME TEXT,
    ROLLBACK_DURATION BIGINT,
    INSTANCES_DEPLOYED INT,
    TAGS HSTORE,

    PRIMARY KEY(EXECUTIONID, ENDTIME)
)
WITH (
    OIDS = FALSE
);
COMMIT;

SELECT CREATE_HYPERTABLE('DEPLOYMENT_PARENT','endtime',chunk_time_interval => interval '3 month',if_not_exists => TRUE);

BEGIN;
CREATE INDEX IF NOT EXISTS DEPLOYMENT_PARENT_TRIGGERED_BY_INDEX ON DEPLOYMENT_PARENT(TRIGGERED_BY,ENDTIME DESC);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_PARENT_TRIGGER_ID_INDEX ON DEPLOYMENT_PARENT(TRIGGER_ID,ENDTIME DESC);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_PARENT_APPID_INDEX ON DEPLOYMENT_PARENT(APPID,ENDTIME DESC);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_PARENT_ACCOUNTID_INDEX ON DEPLOYMENT_PARENT(ACCOUNTID,ENDTIME DESC);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_PARENT_PIPELINE_INDEX ON DEPLOYMENT_PARENT(PIPELINE,ENDTIME DESC);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_PARENT_STATUS_INDEX ON DEPLOYMENT_PARENT(STATUS,ENDTIME DESC);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_PARENT_STARTTIME_INDEX ON DEPLOYMENT_PARENT(STARTTIME,ENDTIME DESC);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_PARENT_DURATION_INDEX ON DEPLOYMENT_PARENT(DURATION,ENDTIME DESC);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_PARENT_SERVICES_GIN_INDEX ON DEPLOYMENT_PARENT USING GIN(SERVICES);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_PARENT_WORKFLOWS_GIN_INDEX ON DEPLOYMENT_PARENT USING GIN(WORKFLOWS);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_PARENT_ARTIFACTS_GIN_INDEX ON DEPLOYMENT_PARENT USING GIN(ARTIFACTS);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_PARENT_CLOUDPROVIDERS_GIN_INDEX ON DEPLOYMENT_PARENT USING GIN(CLOUDPROVIDERS);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_PARENT_ENVIRONMENTS_GIN_INDEX ON DEPLOYMENT_PARENT USING GIN(ENVIRONMENTS);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_PARENT_TAGS_GIN_INDEX ON DEPLOYMENT_PARENT USING GIN(TAGS);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_PARENT_ACCOUNTID_STATUS_INDEX ON DEPLOYMENT_PARENT(ACCOUNTID,STATUS);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_PARENT_ENV_TYPE_INDEX ON DEPLOYMENT_PARENT(ENVTYPES,ENDTIME DESC);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_PARENT_PARENT_EXECUTION_INDEX ON DEPLOYMENT_PARENT(PARENT_EXECUTION,ENDTIME DESC);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_PARENT_STAGENAME_INDEX ON DEPLOYMENT_PARENT(STAGENAME,ENDTIME DESC);
COMMIT;

---------- DEPLOYMENT_PARENT TABLE END ------------
