BEGIN;
CREATE UNIQUE INDEX IF NOT EXISTS UTILIZATION_DATA_UNIQUE_INDEX ON UTILIZATION_DATA(ACCOUNTID, SETTINGID, CLUSTERID, INSTANCEID, INSTANCETYPE, STARTTIME DESC);
COMMIT;

BEGIN;
CREATE UNIQUE INDEX IF NOT EXISTS KUBERNETES_UTILIZATION_DATA_UNIQUE_INDEX ON KUBERNETES_UTILIZATION_DATA(ACCOUNTID, SETTINGID, CLUSTERID, INSTANCEID, INSTANCETYPE, STARTTIME DESC);
COMMIT;





