package io.harness.event.model;

public interface EventConstants {
  String ACCOUNTID = "ACCOUNTID";
  String ACCOUNTNAME = "ACCOUNTNAME";
  String WORKFLOW_EXECUTION_STATUS = "WORKFLOW_EXECUTION_STATUS"; // ABORTED,FAILED,SUCCEEDED etc
  String WORKFLOW_TYPE = "WORKFLOW_TYPE"; // AUTOMATIC / MANUAL
  String WORKFLOW_DURATION = "WORKFLOW_DURATION";
  String AUTOMATIC_WORKFLOW_TYPE = "AUTOMATIC";
  String MANUAL_WORKFLOW_TYPE = "MANUAL";
  String USER_LOGGED_IN = "USER_LOGGED_IN";
}
