package software.wings.audit;

public enum ResourceType {
  CLOUD_PROVIDER,
  ARTIFACT_SERVER,
  COLLABORATION_PROVIDER,
  VERIFICATION_PROVIDER,
  SOURCE_REPO_PROVIDER,
  LOAD_BALANCER,
  CONNECTION_ATTRIBUTES,
  SETTING,
  APPLICATION,
  SERVICE,
  ENVIRONMENT,
  WORKFLOW,
  PIPELINE,
  ROLE,
  ENCRYPTED_RECORDS,
  PROVISIONER,
  TRIGGER,
  DEPLOYMENT_TRIGGER,
  TEMPLATE,
  TEMPLATE_FOLDER,
  USER_GROUP,
  DEPLOYMENT_FREEZE,
  TAG,
  CUSTOM_DASHBOARD,
  SECRET_MANAGER
}
