/*
 * Copyright 2020 Harness Inc. All rights reserved.
 * Use of this source code is governed by the PolyForm Shield 1.0.0 license
 * that can be found in the licenses directory at the root of this repository, also available at
 * https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.
 */

package io.harness.event.model;

public interface EventConstants {
  String ACCOUNT_ID = "ACCOUNT_ID";
  String EMAIL = "email";
  String GROUP_ID = "groupId";
  String ACCOUNT_NAME = "ACCOUNT_NAME";
  String COMPANY_NAME = "COMPANY_NAME";
  String FIRST_NAME = "first_name";
  String LAST_NAME = "last_name";
  String ACCOUNT_TYPE = "ACCOUNT_TYPE";
  String ACCOUNT_STATUS = "accountStatus";
  String DAYS_LEFT_IN_TRIAL = "daysLeftInTrial";
  String USER_INVITE_URL = "userInviteUrl";
  String OAUTH_PROVIDER = "oauthProvider";
  String ACCOUNT_CREATED_AT = "ACCOUNT_CREATED_AT";

  String WORKFLOW_EXECUTION_STATUS = "WORKFLOW_EXECUTION_STATUS"; // ABORTED,FAILED,SUCCEEDED etc
  String WORKFLOW_TYPE = "WORKFLOW_TYPE"; // AUTOMATIC / MANUAL
  String WORKFLOW_DURATION = "WORKFLOW_DURATION";
  String AUTOMATIC_WORKFLOW_TYPE = "AUTOMATIC";
  String MANUAL_WORKFLOW_TYPE = "MANUAL";
  String USER_LOGGED_IN = "USER_LOGGED_IN";
  String SETUP_DATA_TYPE = "SETUP_DATA_TYPE";
  String INSTANCE_COUNT_TYPE = "INSTANCE_COUNT_TYPE";
  String NUMBER_OF_APPLICATIONS = "NUMBER_OF_APPLICATIONS";
  String NUMBER_OF_WORKFLOWS = "NUMBER_OF_WORKFLOWS";
  String NUMBER_OF_ENVIRONMENTS = "NUMBER_OF_ENVIRONMENTS";
  String NUMBER_OF_SERVICES = "NUMBER_OF_SERVICES";
  String NUMBER_OF_PIPELINES = "NUMBER_OF_PIPELINES";
  String NUMBER_OF_TRIGGERS = "NUMBER_OF_TRIGGERS";
  String VERIFICATION_TYPE = "VERIFICATION_TYPE";
  String VERIFICATION_STATUS = "VERIFICATION_STATUS";
  String VERIFICATION_HAS_DATA = "VERIFICATION_HAS_DATA";
  String VERIFICATION_247_CONFIGURED = "VERIFICATION_247_CONFIGURED";
  String IS_ROLLED_BACK = "IS_ROLLED_BACK";
  String IS_24X7_ENABLED = "IS_24X7_ENABLED";

  String LOG_ML_FEEDBACKTYPE = "LOG_ML_FEEDBACK_TYPE";
  String VERIFICATION_STATE_TYPE = "VERIFICATION_STATE_TYPE";
  String APPLICATION_ID = "APPLICATION_ID";
  String APPLICATION_NAME = "APPLICATION_NAME";
  String WORKFLOW_ID = "WORKFLOW_ID";
  String WORKFLOW_NAME = "WORKFLOW_NAME";
  String SERVICE_ID = "SERVICE_ID";
  String SERVICE_NAME = "SERVICE_NAME";
  String ENVIRONMENT_ID = "ENVIRONMENT_ID";
  String ENVIRONMENT_NAME = "ENVIRONMENT_NAME";
  String INSTANCE_COUNT_TOTAL = "TOTAL";
  String INSTANCE_COUNT_GLOBAL_TOTAL = "GLOBAL_TOTAL";
  String INSTANCE_COUNT_NINETY_FIVE_PERCENTILE = "95 PERCENTILE";
}
