/*
 * Copyright 2022 Harness Inc. All rights reserved.
 * Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
 * that can be found in the licenses directory at the root of this repository, also available at
 * https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.
 */

package software.wings.delegatetasks;

import static com.google.common.base.CaseFormat.UPPER_CAMEL;
import static com.google.common.base.CaseFormat.UPPER_UNDERSCORE;

public enum DelegateStateType {
  // Artifact
  ARTIFACT_COLLECTION,
  ARTIFACT_CHECK,

  // SSH
  AWS_NODE_SELECT,
  ELASTIC_LOAD_BALANCER,

  // DC SSH
  DC_NODE_SELECT,

  // AZURE ssh
  AZURE_NODE_SELECT,

  // AZURE Virtual Machine Scale Set
  AZURE_VMSS_SETUP,
  AZURE_VMSS_DEPLOY,
  AZURE_VMSS_ROLLBACK,
  AZURE_VMSS_SWITCH_ROUTES,
  AZURE_VMSS_SWITCH_ROUTES_ROLLBACK,
  AZURE_WEBAPP_SLOT_SETUP,
  AZURE_WEBAPP_SLOT_SWAP,
  AZURE_WEBAPP_SLOT_SHIFT_TRAFFIC,
  AZURE_WEBAPP_SLOT_ROLLBACK,

  // AWS CodeDeploy
  AWS_CODEDEPLOY_STATE,
  AWS_CODEDEPLOY_ROLLBACK,

  // AWS lambda
  AWS_LAMBDA_STATE,
  AWS_LAMBDA_ROLLBACK,

  // AMI
  AWS_AMI_SERVICE_SETUP,
  ASG_AMI_SERVICE_ALB_SHIFT_SETUP,
  AWS_AMI_SERVICE_DEPLOY,
  ASG_AMI_SERVICE_ALB_SHIFT_DEPLOY,
  AWS_AMI_SWITCH_ROUTES,
  ASG_AMI_ALB_SHIFT_SWITCH_ROUTES,
  AWS_AMI_SERVICE_ROLLBACK,
  AWS_AMI_ROLLBACK_SWITCH_ROUTES,
  ASG_AMI_ROLLBACK_ALB_SHIFT_SWITCH_ROUTES,

  // ECS
  ECS_SERVICE_SETUP,
  ECS_RUN_TASK,
  ECS_DAEMON_SERVICE_SETUP,
  ECS_BG_SERVICE_SETUP,
  ECS_BG_SERVICE_SETUP_ROUTE53,
  ECS_SERVICE_DEPLOY,
  ECS_STEADY_STATE_CHECK,
  ECS_LISTENER_UPDATE,
  ECS_ROUTE53_DNS_WEIGHT_UPDATE,
  ECS_SERVICE_SETUP_ROLLBACK,
  ECS_SERVICE_ROLLBACK,
  ECS_ROUTE53_DNS_WEIGHT_UPDATE_ROLLBACK,
  ECS_LISTENER_UPDATE_ROLLBACK,

  // Spot Instance
  SPOTINST_SETUP,
  SPOTINST_ALB_SHIFT_SETUP,
  SPOTINST_DEPLOY,
  SPOTINST_ALB_SHIFT_DEPLOY,
  SPOTINST_LISTENER_UPDATE,
  SPOTINST_LISTENER_ALB_SHIFT,
  SPOTINST_ROLLBACK,
  SPOTINST_LISTENER_UPDATE_ROLLBACK,
  SPOTINST_LISTENER_ALB_SHIFT_ROLLBACK,

  // K8S
  KUBERNETES_SETUP,
  KUBERNETES_DEPLOY,
  KUBERNETES_STEADY_STATE_CHECK,
  GCP_CLUSTER_SETUP,
  K8S_CANARY_DEPLOY,
  K8S_BLUE_GREEN_DEPLOY,
  K8S_DEPLOYMENT_ROLLING,
  K8S_DEPLOYMENT_ROLLING_ROLLBACK,
  KUBERNETES_SWAP_SERVICE_SELECTORS,
  K8S_TRAFFIC_SPLIT,
  K8S_SCALE,
  K8S_DELETE,
  K8S_APPLY,
  RANCHER_RESOLVE,
  RANCHER_K8S_DEPLOYMENT_ROLLING,
  RANCHER_K8S_CANARY_DEPLOY,
  RANCHER_K8S_BLUE_GREEN_DEPLOY,
  RANCHER_KUBERNETES_SWAP_SERVICE_SELECTORS,
  RANCHER_K8S_DELETE,
  RANCHER_K8S_DEPLOYMENT_ROLLING_ROLLBACK,
  ROLLING_NODE_SELECT,
  KUBERNETES_SETUP_ROLLBACK,
  KUBERNETES_DEPLOY_ROLLBACK,

  // Helm
  HELM_DEPLOY,
  HELM_ROLLBACK,

  // PCF
  PCF_SETUP,
  PCF_RESIZE,
  PCF_MAP_ROUTE,
  PCF_UNMAP_ROUTE,
  PCF_BG_MAP_ROUTE,
  PCF_ROLLBACK,
  PCF_PLUGIN,

  // Infra Provisioners
  CLOUD_FORMATION_CREATE_STACK,
  CLOUD_FORMATION_DELETE_STACK,
  CLOUD_FORMATION_ROLLBACK_STACK,
  TERRAFORM_PROVISION,
  TERRAFORM_APPLY,
  TERRAFORM_DESTROY,
  TERRAFORM_ROLLBACK,
  TERRAGRUNT_PROVISION,
  TERRAGRUNT_DESTROY,
  TERRAGRUNT_ROLLBACK,
  SHELL_SCRIPT_PROVISION,
  ARM_ROLLBACK,

  // APM
  APP_DYNAMICS,
  NEW_RELIC,
  INSTANA,
  DYNA_TRACE,
  PROMETHEUS,
  DATA_DOG,
  STACK_DRIVER,
  CLOUD_WATCH,
  APM_VERIFICATION,

  // Logs
  DATA_DOG_LOG,
  BUG_SNAG,
  ELK,
  SPLUNKV2,
  STACK_DRIVER_LOG,
  SUMO,
  LOGZ,
  LOG_VERIFICATION,
  SCALYR,

  // cvng
  CVNG,

  // Issue Tracking
  JIRA_CREATE_UPDATE,
  SERVICENOW_CREATE_UPDATE,

  // Notifications
  EMAIL,

  // Flow Control
  BARRIER,
  RESOURCE_CONSTRAINT,
  APPROVAL,

  // CI System
  JENKINS,
  GCB,
  BAMBOO,

  // Utility
  SHELL_SCRIPT,
  HTTP,
  NEW_RELIC_DEPLOYMENT_MARKER,
  TEMPLATIZED_SECRET_MANAGER,
  CUSTOM_DEPLOYMENT_FETCH_INSTANCES,

  // Command
  COMMAND,

  STAGING_ORIGINAL_EXECUTION,
  APPROVAL_RESUME,
  PHASE_STEP,
  ENV_LOOP_RESUME_STATE,
  REPEAT,
  ENV_STATE,
  ARM_CREATE_RESOURCE,
  PAUSE,
  WAIT,
  SUB_WORKFLOW,
  ENV_LOOP_STATE,
  PHASE,
  FORK,
  ENV_RESUME_STATE,
  AWS_LAMBDA_VERIFICATION,
  ARTIFACT_COLLECT_LOOP_STATE,
  COLLECT_REMAINING_INSTANCES,
  ENV_ROLLBACK_STATE;

  private String displayName = UPPER_UNDERSCORE.to(UPPER_CAMEL, name());

  public String getName() {
    return displayName;
  }
}
