package io.harness.git;

public interface Constants {
  String GIT_YAML_LOG_PREFIX = "GIT_YAML_LOG_ENTRY: ";
  String GIT_TERRAFORM_LOG_PREFIX = "GIT_TERRAFORM_LOG_ENTRY: ";
  String GIT_TRIGGER_LOG_PREFIX = "GIT_TRIGGER_LOG_PREFIX: ";
  String GIT_DEFAULT_LOG_PREFIX = "GIT_DEFAULT_LOG_PREFIX: ";
  String GIT_HELM_LOG_PREFIX = "GIT_HELM_LOG_ENTRY: ";
  String GIT_SETUP_RBAC_PREFIX = "GIT_SETUP_RBAC_PREFIX: ";
  String REPOSITORY = "./repository";
  String GIT_REPO_BASE_DIR = "./repository/${REPO_TYPE}/${ACCOUNT_ID}/${CONNECTOR_ID}/${REPO_NAME}/${REPO_URL_HASH}";
  String REPOSITORY_GIT_FILE_DOWNLOADS = "./repository/gitFileDownloads";
  String REPOSITORY_GIT_FILE_DOWNLOADS_ACCOUNT = "./repository/gitFileDownloads/{ACCOUNT_ID}";
  String REPOSITORY_GIT_FILE_DOWNLOADS_BASE = "./repository/gitFileDownloads/{ACCOUNT_ID}/{CONNECTOR_ID}";
  String REPOSITORY_GIT_FILE_DOWNLOADS_REPO_BASE_DIR = REPOSITORY_GIT_FILE_DOWNLOADS_BASE + "/{REPO_NAME}";
  String REPOSITORY_GIT_FILE_DOWNLOADS_REPO_DIR = REPOSITORY_GIT_FILE_DOWNLOADS_REPO_BASE_DIR + "/{REPO_URL_HASH}";
  String PATH_DELIMITER = "/";
  String HARNESS_IO_KEY_ = "Harness.io";
  String HARNESS_SUPPORT_EMAIL_KEY = "support@harness.io";
  String COMMIT_MESSAGE = "Harness IO Git Sync.\n";
  String EXCEPTION_STRING = "Exception: ";
}
