# Copyright 2022 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

# To be used when building in CIE

FROM us.gcr.io/platform-205701/cie-agent-harness-core-jdk11:latest as builder

RUN mkdir -p /app
ARG GCP_KEY
ENV SERVICE_NAME="event-server"
COPY . /app
WORKDIR /app

ENV BUILD_PURPOSE=DEVELOPMENT

RUN chmod +x \
 /app/build/feature_build.sh \
 /app/scripts/bazel/generate_credentials.sh \
 && /app/scripts/bazel/generate_credentials.sh \
 && /app/build/feature_build.sh $GCP_KEY

FROM us.gcr.io/platform-205701/ubi/ubi-java:8.8 as base
USER root
## Add the capsule JAR and config.yml
COPY --chown=65534:65534 --from=builder \
 /app/dist/event-server/event-server-capsule.jar \
 /app/dist/event-server/keystore.jks \
 /app/dist/event-server/event-service-config.yml \
 /app/dist/event-server/key.pem \
 /app/dist/event-serverr/cert.pem \
 /app/dist/event-server/protocol.info \
 /app/dist/event-server/scripts /opt/harness \
 /app/dockerization/base-images/apm/*.sh \
 /opt/harness/

RUN GRPC_HEALTH_PROBE_VERSION=v0.3.0 \
    && curl -Lso /bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 \
    && chmod +x /bin/grpc_health_probe

RUN chmod +x /opt/harness/*.sh
CMD [ "/opt/harness/run.sh" ]
# USER 65534
# WORKDIR /opt/harness


############################ON PREM#########################
FROM base as onprem
RUN /opt/harness/inject-onprem-apm-bins-into-dockerimage.sh && rm /opt/harness/inject-onprem-apm-bins-into-dockerimage.sh
USER root
RUN microdnf remove tar unzip gzip
USER 65534


############################SAAS#########################
FROM base as saas
RUN /opt/harness/inject-saas-apm-bins-into-dockerimage.sh && rm -rf /opt/harness/inject-saas-apm-bins-into-dockerimage.sh
USER root
