# to be used when building in Jenkins
FROM us.gcr.io/platform-205701/harness/serverjre_8:191
RUN yum install -y hostname tar gzip

# Add the capsule JAR and config.yml
COPY event-server-capsule.jar event-service-config.yml key.pem cert.pem /opt/harness/

COPY scripts /opt/harness

RUN chmod +x /opt/harness/*.sh
RUN mkdir /opt/harness/plugins

WORKDIR /opt/harness

CMD [ "./run.sh" ]
