# to be used when building in Jenkins
FROM harness/serverjre_8:242

# Add the capsule JAR and config.yml
COPY cv-nextgen-capsule.jar AppServerAgent-4.5.0.23604.tar.gz keystore.jks cv-nextgen-config.yml /opt/harness/

COPY scripts /opt/harness

RUN chmod +x /opt/harness/*.sh
RUN mkdir -p /opt/harness/plugins

WORKDIR /opt/harness

CMD [ "./run.sh" ]
