package software.wings.beans;

/**
 * @author Rishi.
 */
public interface CatalogNames {
  String PIPELINE_STENCILS = "PIPELINE_STENCILS";
  String ORCHESTRATION_STENCILS = "ORCHESTRATION_STENCILS";
  String COMMAND_STENCILS = "COMMAND_STENCILS";
  String JENKINS_CONFIG = "JENKINS_CONFIG";
  String JENKINS_BUILD = "JENKINS_BUILD";
  String CONNECTION_ATTRIBUTES = "CONNECTION_ATTRIBUTES";
  String BASTION_HOST_ATTRIBUTES = "BASTION_HOST_ATTRIBUTES";
}
