package software.wings.beans;

/**
 * Created by rishi on 12/22/16.
 */
public enum PhaseStepType {

  SELECT_NODE,
  PROVISION_NODE,
  DISABLE_SERVICE,
  DEPLOY_SERVICE,
  ENABLE_SERVICE,
  VERIFY_SERVICE,
  WRAP_UP,
  PRE_DEPLOYMENT,
  POST_DEPLOYMENT,
  STOP_SERVICE,
  DE_PROVISION_NODE,
  CLUSTER_SETUP,
  CONTAINER_SETUP,
  CONTAINER_DEPLOY,
  START_SERVICE,
  DEPLOY_AWSCODEDEPLOY
}
