FROM harness/manager-openjdk-8u242:x86_64-alpine-jdk8u242-b08

COPY --chown=65534:65534 change-data-capture.jar /opt/harness/
COPY --chown=65534:65534 config.yml /opt/harness/
COPY --chown=65534:65534 scripts /opt/harness/

RUN chmod 500 /opt/harness/*.sh

CMD [ "./run.sh" ]
