# to be used when building in Jenkins
FROM us.gcr.io/platform-205701/harness/serverjre_8:131
RUN yum install -y hostname tar gzip

# we need to install the JCE extensions
COPY common-resources/local_policy.jar /usr/java/jdk1.8.0_131/jre/lib/security/
COPY common-resources/US_export_policy.jar /usr/java/jdk1.8.0_131/jre/lib/security/

# Add the capsule JAR and config.yml
COPY verification-capsule.jar keystore.jks verification-config.yml /opt/harness/

COPY scripts /opt/harness

RUN chmod +x /opt/harness/*.sh
RUN mkdir /opt/harness/plugins

WORKDIR /opt/harness

CMD [ "./run.sh" ]
