FROM redhat/ubi8-minimal:8.4

LABEL name="harness/delegate:immutable" \
      vendor="Harness" \
      maintainer="Harness" \
      version="1.0"

RUN microdnf update \
  && microdnf install --nodocs \
    procps \
    hostname \
    lsof \
    findutils \
  && rm -rf /var/cache/yum \
  && microdnf clean all \
  && mkdir -p /opt/harness-delegate/

COPY immutable-scripts /opt/harness-delegate/

WORKDIR /opt/harness-delegate

RUN chmod -R 755 /opt/harness-delegate \
  && chgrp -R 0 /opt/harness-delegate  \
  && chmod -R g=u /opt/harness-delegate

COPY --from=adoptopenjdk/openjdk8:jre8u242-b08-ubi-minimal /opt/java/openjdk/ /opt/java/openjdk/

ENV HOME=/opt/harness-delegate
ENV JAVA_HOME=/opt/java/openjdk/
ENV PATH="$JAVA_HOME/bin:${PATH}"

# alpn is only needed up to the JDK8u242, after update, it can be removed.
RUN curl -#k https://app.harness.io/public/shared/tools/alpn/release/8.1.13.v20181017/alpn-boot-8.1.13.v20181017.jar -o alpn-boot-8.1.13.v20181017.jar
COPY ./delegate.jar ./delegate.jar

USER 1001

CMD [ "./start.sh" ]