FROM ubuntu:20.04

RUN apt-get update && \
    apt-get -y install curl unzip gnupg2 libgcrypt20 locales && \
    locale-gen en_US.UTF-8 && \
    export LANG=en_US.UTF-8 && \
    apt-get clean

RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

COPY apt-source-list /etc/apt/sources.list.d/kubernetes.list

RUN apt-get update && apt-get install -y kubectl

RUN groupadd -r harness -g 1000560000 && useradd --no-log-init -r -u 1000560000 -g harness harness

COPY scripts /opt/harness-delegate/

RUN chmod +x /opt/harness-delegate/*.sh

RUN chown harness /opt/harness-delegate /opt/harness-delegate/*.sh

RUN chgrp harness /opt/harness-delegate /opt/harness-delegate/*.sh

RUN mkdir -p /home/harness

RUN chown harness /home/harness

RUN chgrp harness /home/harness

USER harness

RUN mkdir -p /home/harness/bin

ENV PATH="/home/harness/bin:${PATH}"

WORKDIR /opt/harness-delegate

RUN mkdir -m 777 -p client-tools/go-template/v0.4 \
    && curl -s -L -o client-tools/go-template/v0.4/go-template https://app.harness.io/public/shared/tools/go-template/release/v0.4/bin/linux/amd64/go-template \
    && mkdir -m 777 -p client-tools/harness-pywinrm/v0.4-dev \
    && curl -s -L -o client-tools/harness-pywinrm/v0.4-dev/harness-pywinrm https://app.harness.io/public/shared/tools/harness-pywinrm/release/v0.4-dev/bin/linux/amd64/harness-pywinrm \
    && mkdir -m 777 -p client-tools/helm/v2.13.1 && curl -s -L -o client-tools/helm/v2.13.1/helm https://app.harness.io/public/shared/tools/helm/release/v2.13.1/bin/linux/amd64/helm \
    && mkdir -m 777 -p client-tools/chartmuseum/v0.13.0 \
    && curl -s -L -o client-tools/chartmuseum/v0.13.0/chartmuseum https://app.harness.io/public/shared/tools/chartmuseum/release/v0.8.2/bin/linux/amd64/chartmuseum \
    && mkdir -m 777 -p client-tools/tf-config-inspect/v1.0/linux/amd64 \
    && curl -s -L -o client-tools/tf-config-inspect/v1.0/linux/amd64/terraform-config-inspect https://app.harness.io/public/shared/tools/terraform-config-inspect/v1.0/linux/amd64/terraform-config-inspect \
    && mkdir -m 777 -p client-tools/oc/v4.2.16 \
    && curl -s -L -o client-tools/oc/v4.2.16/oc https://app.harness.io/public/shared/tools/oc/release/v4.2.16/bin/linux/amd64/oc \
    && mkdir -m 777 -p client-tools/kustomize/v3.5.4 \
    && curl -s -L -o client-tools/kustomize/v3.5.4/kustomize https://app.harness.io/public/shared/tools/kustomize/release/v3.5.4/bin/linux/amd64/kustomize \
    && mkdir -m 777 -p client-tools/scm/72f01538/linux/amd64 \
    && curl -s -L -o client-tools/scm/72f01538/linux/amd64/scm https://app.harness.io/public/shared/tools/scm/release/72f01538/bin/linux/amd64/scm \
    && chmod -R 755 /opt/harness-delegate


ARG watcher_version
RUN curl -s https://app.harness.io/storage/wingsdelegates/jre/openjdk-8u242/jre_x64_linux_8u242b08.tar.gz | tar -xz
RUN curl -#k https://app.harness.io/public/shared/watchers/builds/openjdk-8u242/$watcher_version/watcher.jar -o watcher.jar

CMD ./entrypoint.sh && bash -c ' \
    while [[ ! -e watcher.log ]]; do sleep 1s; done; tail -F watcher.log & \
    while [[ ! -e delegate.log ]]; do sleep 1s; done; tail -F delegate.log'
