# to be used when some instrumentation is needed
FROM base_delegate

WORKDIR /opt/harness-delegate

RUN mkdir -p /opt/harness-delegate/file-leak-detector

RUN mkdir -p /opt/harness-delegate/file-leak-detector/reports

RUN curl -o /opt/harness-delegate/file-leak-detector/file-leak-detector.jar https://repo1.maven.org/maven2/org/kohsuke/file-leak-detector/1.13/file-leak-detector-1.13-jar-with-dependencies.jar

RUN curl -k -L https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u242-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u242b08.tar.gz -o jdk8u242.tar.gz

RUN tar -xvf jdk8u242.tar.gz

RUN rm jdk8u242.tar.gz

ENV JDK_BINARY=jdk8u242-b08/bin/java

ENV INSTRUMENTATION=-javaagent:file-leak-detector/file-leak-detector.jar=trace=file-leak-detector/reports/trace.txt,error=file-leak-detector/reports/error.txt,strong