# to be used when building in Jenkins
FROM us.gcr.io/platform-205701/ubuntu:safe-ubuntu18.04-sec1509

RUN apt-get update && apt-get -y upgrade && apt-get -y install apt-utils curl unzip apt-transport-https gnupg2 locales \
&& locale-gen en_US.UTF-8 && export LANG=en_US.UTF-8

RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

COPY apt-source-list /etc/apt/sources.list.d/kubernetes.list

RUN apt-get update && apt-get install -y kubectl

COPY scripts /opt/harness-delegate/

RUN chmod +x /opt/harness-delegate/*.sh

WORKDIR /opt/harness-delegate

RUN curl -s https://app.harness.io/storage/wingsdelegates/jre/openjdk-8u242/jre_x64_linux_8u242b08.tar.gz | tar -xz

CMD ./entrypoint.sh && bash -c ' \
    while [[ ! -e watcher.log ]]; do sleep 1s; done; tail -F watcher.log & \
    while [[ ! -e delegate.log ]]; do sleep 1s; done; tail -F delegate.log'
