# Copyright 2022 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

FROM redhat/ubi8-minimal:8.8

LABEL name="harness/delegate:ubi-minimal" \
      vendor="Harness" \
      maintainer="Harness" \
      version="1.0"    

RUN microdnf update \
 && microdnf install --nodocs \
    unzip \
    tar \
    procps \
    hostname \
    lsof \
    findutils \
 && rm -rf /var/cache/yum \
 && microdnf clean all \
 && mkdir -p /opt/harness-delegate/

COPY scripts /opt/harness-delegate/

WORKDIR /opt/harness-delegate

ARG disable_client_tools
ARG TARGETARCH
ENV LANG=en_US.UTF-8
RUN ./client_tools.sh $disable_client_tools $TARGETARCH\
    && chmod -R 755 /opt/harness-delegate \
    && chgrp -R 0 /opt/harness-delegate  \
    && chmod -R g=u /opt/harness-delegate \
    && chown -R 1001 /opt/harness-delegate

ENV HOME=/opt/harness-delegate
ENV CLIENT_TOOLS_DOWNLOAD_DISABLED=$disable_client_tools

USER 1001
COPY --chown=1001 --from=adoptopenjdk/openjdk11:jre-11.0.14_9-ubi-minimal /opt/java/openjdk/ ./jdk-11.0.14+9-jre/

ARG watcher_version
RUN curl -#k https://app.harness.io/public/shared/watchers/builds/openjdk-8u242/$watcher_version/watcher.jar -o watcher.jar
CMD ./entrypoint.sh && bash -c ' \
    while [[ ! -e watcher.log ]]; do sleep 1s; done; tail -F watcher.log & \
    while [[ ! -e delegate.log ]]; do sleep 1s; done; tail -F delegate.log'