# to be used when building in Jenkins
FROM harness/serverjre_8:131
RUN yum install -y ntp net-tools telnet vim

# we need to install the JCE extensions
COPY dockerization/common-resources/local_policy.jar /usr/java/jdk1.8.0_131/jre/lib/security/
COPY dockerization/common-resources/US_export_policy.jar /usr/java/jdk1.8.0_131/jre/lib/security/

# Add the capsule JAR and config.yml
COPY docker-image-files/delegate-0.0.1-SNAPSHOT-capsule.jar  /opt/harness-delegate/

COPY dockerization/manager/scripts /opt/harness-delegate/

RUN chmod +x /opt/harness-delegate/*.sh

WORKDIR /opt/harness-delegate

CMD ./run.sh
