# to be used when building in Jenkins
FROM ubuntu:20.04

RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install curl unzip gnupg2 locales && \
    locale-gen en_US.UTF-8 && \
    export LANG=en_US.UTF-8 && \
    apt-get clean

RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

COPY apt-source-list /etc/apt/sources.list.d/kubernetes.list

RUN apt-get update && apt-get install -y kubectl

RUN useradd --no-log-init -r -u 1000560000 harness

COPY scripts /opt/harness-delegate/

RUN chmod 777 /opt/harness-delegate

RUN chmod +x /opt/harness-delegate/*.sh
RUN chmod g+x /opt/harness-delegate/*.sh

RUN chown harness /opt/harness-delegate /opt/harness-delegate/*.sh

RUN mkdir -p /home/harness \
    && chown harness:harness /home/harness -R \
    && chmod 777 /home/harness

USER harness

ENV HOME="/home/harness"

RUN mkdir -p /home/harness/bin

ENV PATH="/home/harness/bin:${PATH}"

WORKDIR /opt/harness-delegate

RUN curl -s https://app.harness.io/storage/wingsdelegates/jre/openjdk-8u242/jre_x64_linux_8u242b08.tar.gz | tar -xz
RUN chmod 666 /opt/harness-delegate/jdk8u242-b08-jre/lib/security/cacerts
RUN curl -#k https://app.harness.io/public/shared/watchers/builds/openjdk-8u242/72305/watcher.jar -o watcher.jar

CMD ./entrypoint.sh && bash -c ' \
    while [[ ! -e watcher.log ]]; do sleep 1s; done; tail -F watcher.log & \
    while [[ ! -e delegate.log ]]; do sleep 1s; done; tail -F delegate.log'
