# to be used when building in Jenkins
FROM harness/serverjre_8:131
RUN yum install -y ntp net-tools telnet vim unzip

# we need to install the JCE extensions
COPY dockerization/common-resources/local_policy.jar /usr/java/jdk1.8.0_131/jre/lib/security/
COPY dockerization/common-resources/US_export_policy.jar /usr/java/jdk1.8.0_131/jre/lib/security/

COPY dockerization/delegate/scripts /opt/harness-delegate/

RUN chmod +x /opt/harness-delegate/*.sh

WORKDIR /opt/harness-delegate

CMD ./run.sh
