# Copyright 2022 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

FROM ubuntu:20.04

RUN apt-get update && \
    apt-get -y install curl unzip gnupg2 libgcrypt20 locales && \
    locale-gen en_US.UTF-8 && \
    export LANG=en_US.UTF-8 && \
    apt-get clean
ARG TARGETARCH
RUN curl -LO https://dl.k8s.io/release/v1.25.8/bin/linux/$TARGETARCH/kubectl
RUN chmod +x kubectl
RUN mv kubectl /usr/bin/kubectl

COPY scripts /opt/harness-delegate/

RUN chmod +x /opt/harness-delegate/*.sh

WORKDIR /opt/harness-delegate

ARG TARGETARCH
ENV LANG=en_US.UTF-8

RUN ./client_tools.sh false $TARGETARCH && chmod -R 755 /opt/harness-delegate

COPY --from=adoptopenjdk/openjdk11:jre-11.0.14_9 /opt/java/openjdk/ ./jdk-11.0.14+9-jre/

ARG watcher_version
RUN curl -#k https://app.harness.io/public/shared/watchers/builds/openjdk-8u242/$watcher_version/watcher.jar -o watcher.jar

CMD ./entrypoint.sh && bash -c ' \
    while [[ ! -e watcher.log ]]; do sleep 1s; done; tail -F watcher.log & \
    while [[ ! -e delegate.log ]]; do sleep 1s; done; tail -F delegate.log'
