# to be used when building in Jenkins
FROM ubuntu:18.04

RUN apt-get update && apt-get -y upgrade && apt-get -y install apt-utils curl unzip apt-transport-https gnupg2

RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

COPY dockerization/delegate/apt-source-list /etc/apt/sources.list.d/kubernetes.list

RUN apt-get update && apt-get install -y kubectl

RUN groupadd -r harness -g 1000560000 && useradd --no-log-init -r -u 1000560000 -g harness harness

COPY dockerization/delegate/scripts /opt/harness-delegate/

RUN chmod +x /opt/harness-delegate/*.sh

RUN chown harness /opt/harness-delegate /opt/harness-delegate/*.sh

RUN chgrp harness /opt/harness-delegate /opt/harness-delegate/*.sh

RUN mkdir -p /home/harness

RUN chown harness /home/harness

RUN chgrp harness /home/harness

USER harness

WORKDIR /opt/harness-delegate

RUN curl -s https://app.harness.io/storage/wingsdelegates/jre/8u191/jre-8u191-linux-x64.tar.gz | tar -xz

CMD ./start.sh && bash -c ' \
    while [[ ! -e watcher.log ]]; do \
      sleep 1s; \
    done; \
    tail -F watcher.log & \
    while [[ ! -e delegate.log ]]; do \
      sleep 1s; \
    done; \
    tail -F delegate.log'
