# Copyright 2022 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

FROM ubuntu:20.04

RUN apt-get update && \
    apt-get -y install curl unzip gnupg2 libgcrypt20 locales && \
    locale-gen en_US.UTF-8 && \
    export LANG=en_US.UTF-8 && \
    apt-get clean

ARG TARGETARCH
RUN curl -LO https://dl.k8s.io/release/v1.25.8/bin/linux/$TARGETARCH/kubectl
RUN chmod +x kubectl
RUN mv kubectl /usr/bin/kubectl

RUN groupadd -r harness -g 1000560000 && useradd --no-log-init -r -u 1000560000 -g harness harness

COPY scripts /opt/harness-delegate/

RUN chmod +x /opt/harness-delegate/*.sh

RUN chown harness /opt/harness-delegate /opt/harness-delegate/*.sh

RUN chgrp harness /opt/harness-delegate /opt/harness-delegate/*.sh

RUN mkdir -p /home/harness

RUN chown harness /home/harness

RUN chgrp harness /home/harness

USER harness

RUN mkdir -p /home/harness/bin

ENV PATH="/home/harness/bin:${PATH}"

WORKDIR /opt/harness-delegate

RUN ./client_tools.sh false amd64 && chmod -R 755 /opt/harness-delegate

RUN curl -s https://app.harness.io/public/shared/jre/openjdk-11.0.14_9/OpenJDK11U-jre_x64_linux_hotspot_11.0.14_9.tar.gz | tar -xz

ARG watcher_version
RUN curl -#k https://app.harness.io/public/shared/watchers/builds/openjdk-8u242/$watcher_version/watcher.jar -o watcher.jar

CMD ./entrypoint.sh && bash -c ' \
    while [[ ! -e watcher.log ]]; do sleep 1s; done; tail -F watcher.log & \
    while [[ ! -e delegate.log ]]; do sleep 1s; done; tail -F delegate.log'
