# CIE AGENT - JAVA+GO+BUILD TOOLS

# Usage: Used to run CIE builds for harness-core compilation, test
# Test image locally by running this command:
#
# $ docker build \
#     -f Dockerfile-java-go-cie-agent" \
#     -t <tag> \
#     .

FROM us.gcr.io/platform-205701/ubi/ubi-java:latest

USER root

#Disabling Subscription of RedHat
RUN sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/subscription-manager.conf

RUN mkdir -p /deployments

# JAVA_APP_DIR is used by run-java.sh for finding the binaries
ENV JAVA_APP_DIR=/deployments \
    JAVA_MAJOR_VERSION=11

# Add run script as /deployments/run-java.sh and make it executable
COPY run-java.sh /deployments/
RUN chmod 755 /deployments/run-java.sh

##TODO: Check mongo is req
COPY mongodb-org-4.4.repo /etc/yum.repos.d/
COPY google-cloud-sdk.repo /etc/yum.repos.d/

ENV LC_ALL en_US.UTF-8
ENV CC /usr/bin/gcc
ENV CXX /usr/bin/g++

##TODO: google-cloud-cli can be removed, update pipelines for the same
RUN yum update -y \
    && yum install -y hostname wget unzip git mongodb-org-shell google-cloud-cli gcc gcc-c++ jq bc zlib-devel\
    && yum install -y autoconf binutils gdb glibc-devel redhat-rpm-config rpm-build \
    && git --version \
    && curl -Lo /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.7.4/bazelisk-linux-amd64 \
    && chown root:root /usr/local/bin/bazel \
    && chmod 0755 /usr/local/bin/bazel \
    && bazel version \
    && cd / \
    && rm -rf /tmp/*

CMD [ "/deployments/run-java.sh" ]

RUN curl -O https://dl.google.com/go/go1.17.8.linux-amd64.tar.gz \
    && tar -xvf go1.17.8.linux-amd64.tar.gz \
    && mv go/ /usr/local/ \
    && rm -rf go1.17.8.linux-amd64.tar.gz

ENV PATH ${PATH}:/opt/gsutil:/usr/local/go/bin

ENV GOROOT /usr/local/go
ENV GOPATH /usr/local