# Copyright 2022 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

# CIE AGENT - JAVA+GO+BUILD TOOLS

# Usage: Used to run CIE builds for harness-core compilation, test
# Test image locally by running this command:
#
# $ docker build \
#     -f Dockerfile-java-go-cie-agent" \
#     -t <tag> \
#     .

FROM us.gcr.io/platform-205701/ubi/ubi-java:8.7

USER root

RUN microdnf install yum

RUN mkdir -p /deployments

# JAVA_APP_DIR is used by run-java.sh for finding the binaries
ENV JAVA_APP_DIR=/deployments \
    JAVA_MAJOR_VERSION=11

# Add run script as /deployments/run-java.sh and make it executable
COPY run-java.sh /deployments/
RUN chmod 755 /deployments/run-java.sh

##TODO: Check mongo is req
COPY mongodb-org-4.4.repo /etc/yum.repos.d/
COPY google-cloud-sdk.repo /etc/yum.repos.d/

ENV LC_ALL en_US.UTF-8
ENV CC /usr/bin/gcc
ENV CXX /usr/bin/g++

ARG KUBECTL_VERSION=v1.13.2
ARG PLATFORM=linux
ARG HELM_VERSION=2.17.0
ARG SONARQUBE_VERSION=4.7.0.2747

##TODO: google-cloud-cli can be removed, update pipelines for the same
RUN yum install -y nodejs python mongodb-org-shell google-cloud-cli autoconf binutils gdb glibc-devel redhat-rpm-config rpm-build wget git gcc gcc-c++ jq bc zlib-devel yum-utils --nodocs --skip-broken \
    && yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo\
    && yum install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin \
    && git --version \
    && curl -Lo /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.7.4/bazelisk-linux-amd64 \
    && chown root:root /usr/local/bin/bazel \
    && chmod 0755 /usr/local/bin/bazel \
    && bazel version \
    && cd / \
    && rm -rf /tmp/* \
    && yum clean all \
    && rm -rf /var/tmp/yum-* \
    && curl  -s -L -o kubectl https://app.harness.io/storage/harness-download/kubernetes-release/release/${KUBECTL_VERSION}/bin/${PLATFORM}/amd64/kubectl \
    && chmod +x kubectl \
    && mv kubectl /usr/bin \
    && wget -q https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz -O - | tar -xzO linux-amd64/helm > /usr/local/bin/helm \
    && chmod +x /usr/local/bin/helm \
    && wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONARQUBE_VERSION}-linux.zip \
    && unzip sonar-scanner-cli-${SONARQUBE_VERSION}-linux.zip\
    && mv sonar-scanner-${SONARQUBE_VERSION}-linux /opt/ \
    && rm -f sonar-scanner-cli-${SONARQUBE_VERSION}-linux.zip \
    && wget https://archive.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz \
    && tar -xf apache-maven-3.6.1-bin.tar.gz && mv apache-maven-3.6.1/ /usr/local/src/apache-maven \
    && echo "export M2_HOME=/usr/local/src/apache-maven \
    && export PATH=\${M2_HOME}/bin:\${PATH}" > /etc/profile.d/maven.sh \
    && chmod +x /etc/profile.d/maven.sh \
    && source /etc/profile.d/maven.sh \
    && rm apache-maven-3.6.1-bin.tar.gz \
    && cd / && rm -rf /tmp/*

CMD [ "/deployments/run-java.sh" ]

RUN curl -O https://dl.google.com/go/go1.18.linux-amd64.tar.gz \
    && tar -xvf go1.18.linux-amd64.tar.gz \
    && mv go/ /usr/local/ \
    && rm -rf go1.18.linux-amd64.tar.gz

ENV PATH ${PATH}:/opt/gsutil:/usr/local/go/bin:/opt/sonar-scanner-${SONARQUBE_VERSION}-linux/bin

ENV GOROOT /usr/local/go
ENV GOPATH /usr/local
