ARG BUILD_TAG=?
ARG REGISTRY_PATH=?
ARG REPO_PATH=?
ARG BUILD_TYPE=?
ARG SERVICE_NAME=?
FROM ${REGISTRY_PATH}/${REPO_PATH}/${BUILD_TYPE}-${SERVICE_NAME}:${BUILD_TAG}

ARG APM_BINS=?

ADD --chown=65534:65534 --chmod=711 ./${APM_BINS} /opt/harness/
