/*
 * Copyright 2021 Harness Inc. All rights reserved.
 * Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
 * that can be found in the licenses directory at the root of this repository, also available at
 * https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.
 */

/**
 *
 */

package software.wings.beans;

/**
 * Some of the bean objects are not entities in mongo db. They are used as embedded objects.
 * In other words, they don't extend Base or UuidAware.
 *
 * @author rktummala on 10/28/17
 */
public interface ObjectType {
  String PHASE = "PHASE";
  String PHASE_STEP = "PHASE_STEP";
  String STEP = "STEP";
  String NAME_VALUE_PAIR = "NAME_VALUE_PAIR";
  String TEMPLATE_EXPRESSION = "TEMPLATE_EXPRESSION";
  String NOTIFICATION_RULE = "NOTIFICATION_RULE";

  String VARIABLE = "VARIABLE";
  String FAILURE_STRATEGY = "FAILURE_STRATEGY";
  String STEP_SKIP_STRATEGY = "STEP_SKIP_STRATEGY";
  String NOTIFICATION_GROUP = "NOTIFICATION_GROUP";
  String PIPELINE_STAGE = "PIPELINE_STAGE";
  String COMMAND_UNIT = "COMMAND_UNIT";
  String ECS_CONTAINER_TASK = "ECS_CONTAINER_TASK";
  String KUBERNETES_CONTAINER_TASK = "KUBERNETES_CONTAINER_TASK";
  String AWS_LAMBDA_SPEC = "AWS_LAMBDA_SPEC";
  String CONTAINER_DEFINITION = "CONTAINER_DEFINITION";
  String LOG_CONFIGURATION = "LOG_CONFIGURATION";
  String PORT_MAPPING = "PORT_MAPPING";
  String STORAGE_CONFIGURATION = "STORAGE_CONFIGURATION";
  String LAMBDA_SPECIFICATION = "LAMBDA_SPECIFICATION";
  String DEFAULT_SPECIFICATION = "DEFAULT_SPECIFICATION";
  String FUNCTION_SPECIFICATION = "FUNCTION_SPECIFICATION";
  String SETTING_ATTRIBUTE = "SETTING_ATTRIBUTE";
  String SETTING_VALUE = "SETTING_VALUE";
  String APPLICATION_DEFAULTS = "APPLICATION_DEFAULTS";
  String ACCOUNT_DEFAULTS = "ACCOUNT_DEFAULTS";
  String USAGE_RESTRICTIONS = "USAGE_RESTRICTIONS";
  String TRIGGER_CONDITION = "TRIGGER_CONDITION";
  String ARTIFACT_SELECTION = "ARTIFACT_SELECTION";
  String CLOUD_PROVIDER_INFRASTRUCTURE = "CLOUD_PROVIDER_INFRASTRUCTURE";
  String CONDITION = "CONDITION";
  String PAYLOAD_SOURCE = "PAYLOAD_SOURCE";
  String ACTION = "ACTION";
  String TRIGGER_ARTIFACT_VARIABLE = "TRIGGER_ARTIFACT_VARIABLE";
  String WEBHOOK_EVENT = "WEBHOOK_EVENT";
  String TRIGGER_VARIABLE = "TRIGGER_VARIABLE";
  String TRIGGER_ARTIFACT_VALUE = "TRIGGER_ARTIFACT_VALUE";
  String TEMPLATE = "TEMPLATE";
  String MANIFEST_SELECTION = "MANIFEST_SELECTION";
  String APPLICATION_FILTER = "APPLICATION_FILTER";
  String ENVIRONMENT_FILTER = "ENVIRONMENT_FILTER";
  String SERVICE_FILTER = "SERVICE_FILTER";
}
