FROM us.gcr.io/platform-205701/alpine:safe-alpine3.12-sec1695

RUN mkdir -p /opt/harness/

# Note: Apm agent is pulled from platform gcr bucket while executing jenkins job: portal-alpine-base-apm
COPY ./AppServerAgent-20.8.0.30686.zip /opt/harness/
