# Use this file to generate new safe image or add new packages
# Filename: Dockerfile
FROM us.gcr.io/platform-205701/alpine:base
CMD ["/bin/sh"]

#upgrade packages except openjdk8. Note: harness has hard dependency on existing 242 version
RUN apk upgrade --available --ignore openjdk8 openjdk8-jre openjdk8-jre-lib openjdk8-jre-base && sync

#pip upgrade: install package pip-uprade-outdated, upgrade packages and uninstall additional package
RUN pip list --outdated
RUN pip install pip-upgrade-outdated
RUN pip_upgrade_outdated -3 -v -x distlib -x rsa -x docutils
RUN pip list --outdated
RUN pip uninstall -y pip-upgrade-outdated

#Nothing to add, Just ensuring packages related with Openjdk8 is not update
RUN apk list --installed | grep -i openjdk8
