# to be used when building in Jenkins
FROM harness/serverjre_8:191
RUN yum install -y hostname tar gzip

# Add the capsule JAR and config.yml
COPY docker-image-files/rest-capsule.jar docker-image-files/AppServerAgent-4.5.0.23604.tar.gz keystore.jks docker-image-files/config.yml docker-image-files/hazelcast.xml /opt/harness/

COPY dockerization/manager/scripts /opt/harness

RUN chmod +x /opt/harness/*.sh
RUN mkdir /opt/harness/plugins

WORKDIR /opt/harness

CMD [ "./run.sh" ]
