# Copyright 2022 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

FROM us.gcr.io/platform-205701/ubi/ubi-java:latest
USER root
RUN yum install -y hostname tar gzip python3

# Add the capsule JAR and config.yml
COPY --chown=65534:65534 batch-processing-capsule.jar /opt/harness/
COPY --chown=65534:65534 batch-processing-config.yml  /opt/harness/
COPY --chown=65534:65534 protocol.info /opt/harness/

RUN pip3 install awscli

#Download AzCopy
RUN curl -LO https://aka.ms/downloadazcopy-v10-linux && tar -xvf downloadazcopy-v10-linux && cp ./azcopy_linux_amd64_*/azcopy /usr/local/bin/ \
    && chmod +x /usr/local/bin/azcopy

ENV AZCOPY_LOG_LOCATION=/opt/harness/azlogs

COPY --chown=65534:65534 scripts /opt/harness

RUN chmod +x /opt/harness/*.sh && chmod 700 -R /opt/harness/ && chown -R 65534:65534 /opt/harness/

CMD [ "./run.sh" ]

USER 65534