BEGIN;
ALTER TABLE KUBERNETES_UTILIZATION_DATA ADD COLUMN MAXCPU DOUBLE PRECISION;
ALTER TABLE KUBERNETES_UTILIZATION_DATA ADD COLUMN MAXMEMORY DOUBLE PRECISION;
ALTER TABLE BILLING_DATA ADD COLUMN INSTANCENAME TEXT;
COMMIT;