BEGIN;
ALTER TABLE UTILIZATION_DATA RENAME COLUMN SETTINGID TO CLUSTERID;
ALTER TABLE KUBERNETES_UTILIZATION_DATA RENAME COLUMN SETTINGID TO CLUSTERID;
CREATE UNIQUE INDEX IF NOT EXISTS BILLING_DATA_UNIQUE_INDEX ON BILLING_DATA(ACCOUNTID, CLUSTERID, INSTANCEID, INSTANCETYPE, STARTTIME DESC);
COMMIT;