BEGIN;
ALTER TABLE UTILIZATION_DATA ADD COLUMN CLUSTERID TEXT;
ALTER TABLE KUBERNETES_UTILIZATION_DATA ADD COLUMN CLUSTERID TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS BILLING_DATA_UNIQUE_INDEX ON BILLING_DATA(
    ACCOUNTID, SETTINGID, CLUSTERID, INSTANCEID, INSTANCETYPE, STARTTIME DESC);
COMMIT;