---------- BILLING_DATA TABLE START ------------
BEGIN;
CREATE TABLE IF NOT EXISTS BILLING_DATA (
	STARTTIME TIMESTAMPTZ NOT NULL,
	ENDTIME TIMESTAMPTZ NOT NULL,
	ACCOUNTID TEXT NOT NULL,
	SETTINGID TEXT,
	INSTANCEID TEXT NOT NULL,
	INSTANCETYPE TEXT NOT NULL,
	BILLINGACCOUNTID TEXT,
	CLUSTERID TEXT,
	CLUSTERNAME TEXT,
	APPID TEXT,
	SERVICEID TEXT,
	ENVID TEXT,
	CLOUDPROVIDERID TEXT,
	PARENTINSTANCEID TEXT,
	REGION TEXT,
	LAUNCHTYPE TEXT,
	CLUSTERTYPE TEXT,
	WORKLOADNAME TEXT,
	WORKLOADTYPE TEXT,
	NAMESPACE TEXT,
	CLOUDSERVICENAME TEXT,
	CLOUDPROVIDER TEXT,
	BILLINGAMOUNT DOUBLE PRECISION  NOT NULL,
	CPUBILLINGAMOUNT DOUBLE PRECISION,
	MEMORYBILLINGAMOUNT DOUBLE PRECISION,
	IDLECOST DOUBLE PRECISION,
	CPUIDLECOST DOUBLE PRECISION,
	MEMORYIDLECOST DOUBLE PRECISION,
	USAGEDURATIONSECONDS DOUBLE PRECISION,
	CPUUNITSECONDS DOUBLE PRECISION,
	MEMORYMBSECONDS DOUBLE PRECISION,
	MAXCPUUTILIZATION DOUBLE PRECISION,
	MAXMEMORYUTILIZATION DOUBLE PRECISION,
	AVGCPUUTILIZATION DOUBLE PRECISION,
	AVGMEMORYUTILIZATION DOUBLE PRECISION
);
COMMIT;
SELECT CREATE_HYPERTABLE('BILLING_DATA','starttime',if_not_exists => TRUE);

BEGIN;
CREATE INDEX IF NOT EXISTS BILLING_DATA_ACCOUNTID_INDEX ON BILLING_DATA(ACCOUNTID, STARTTIME DESC);
CREATE INDEX IF NOT EXISTS BILLING_DATA_APPID_COMPOSITE_INDEX ON BILLING_DATA(ACCOUNTID, APPID,STARTTIME DESC);
CREATE INDEX IF NOT EXISTS BILLING_DATA_WORKLOADNAME_COMPOSITE_INDEX ON BILLING_DATA(ACCOUNTID, CLUSTERID, WORKLOADNAME, STARTTIME DESC);
CREATE INDEX IF NOT EXISTS BILLING_DATA_NAMESPACE_COMPOSITE_INDEX ON BILLING_DATA(ACCOUNTID, CLUSTERID, NAMESPACE, STARTTIME DESC);
CREATE INDEX IF NOT EXISTS BILLING_DATA_CLUSTERID_COMPOSITE_INDEX ON BILLING_DATA(ACCOUNTID, CLUSTERID, STARTTIME DESC);
CREATE INDEX IF NOT EXISTS BILLING_DATA_CLOUDPROVIDERID_COMPOSITE_INDEX ON BILLING_DATA(ACCOUNTID, CLOUDPROVIDERID, STARTTIME DESC);
COMMIT;
---------- BILLING_DATA TABLE END ------------
