// Copyright 2021 Harness Inc. All rights reserved.
// Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
// that can be found in the licenses directory at the root of this repository, also available at
// https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

// Code generated by MockGen. DO NOT EDIT.
// Source: plugin.go

// Package tasks is a generated GoMock package.
package tasks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	proto "github.com/wings-software/portal/product/ci/engine/proto"
)

// MockPluginTask is a mock of PluginTask interface.
type MockPluginTask struct {
	ctrl     *gomock.Controller
	recorder *MockPluginTaskMockRecorder
}

// MockPluginTaskMockRecorder is the mock recorder for MockPluginTask.
type MockPluginTaskMockRecorder struct {
	mock *MockPluginTask
}

// NewMockPluginTask creates a new mock instance.
func NewMockPluginTask(ctrl *gomock.Controller) *MockPluginTask {
	mock := &MockPluginTask{ctrl: ctrl}
	mock.recorder = &MockPluginTaskMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPluginTask) EXPECT() *MockPluginTaskMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockPluginTask) Run(ctx context.Context) (*proto.Artifact, int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(*proto.Artifact)
	ret1, _ := ret[1].(int32)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Run indicates an expected call of Run.
func (mr *MockPluginTaskMockRecorder) Run(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockPluginTask)(nil).Run), ctx)
}
