// Copyright 2020 Harness Inc. All rights reserved.
// Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
// that can be found in the licenses directory at the root of this repository, also available at
// https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

// Code generated by MockGen. DO NOT EDIT.
// Source: logproxy_client.go

// Package grpcclient is a generated GoMock package.
package grpcclient

import (
	gomock "github.com/golang/mock/gomock"
	proto "github.com/wings-software/portal/product/ci/engine/proto"
	reflect "reflect"
)

// MockLogProxyClient is a mock of LogProxyClient interface.
type MockLogProxyClient struct {
	ctrl     *gomock.Controller
	recorder *MockLogProxyClientMockRecorder
}

// MockLogProxyClientMockRecorder is the mock recorder for MockLogProxyClient.
type MockLogProxyClientMockRecorder struct {
	mock *MockLogProxyClient
}

// NewMockLogProxyClient creates a new mock instance.
func NewMockLogProxyClient(ctrl *gomock.Controller) *MockLogProxyClient {
	mock := &MockLogProxyClient{ctrl: ctrl}
	mock.recorder = &MockLogProxyClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogProxyClient) EXPECT() *MockLogProxyClientMockRecorder {
	return m.recorder
}

// CloseConn mocks base method.
func (m *MockLogProxyClient) CloseConn() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseConn")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseConn indicates an expected call of CloseConn.
func (mr *MockLogProxyClientMockRecorder) CloseConn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseConn", reflect.TypeOf((*MockLogProxyClient)(nil).CloseConn))
}

// Client mocks base method.
func (m *MockLogProxyClient) Client() proto.LogProxyClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Client")
	ret0, _ := ret[0].(proto.LogProxyClient)
	return ret0
}

// Client indicates an expected call of Client.
func (mr *MockLogProxyClientMockRecorder) Client() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Client", reflect.TypeOf((*MockLogProxyClient)(nil).Client))
}
