package io.harness.perpetualtask;

public enum PerpetualTaskState {
  TASK_UNASSIGNED,
  TASK_PAUSED,
  NO_DELEGATE_INSTALLED,
  NO_DELEGATE_AVAILABLE,
  NO_ELIGIBLE_DELEGATES,
  TASK_ASSIGNED,
  TASK_RUN_SUCCEEDED,
  TASK_RUN_FAILED
}
