// Copyright 2020 Harness Inc. All rights reserved.
// Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
// that can be found in the licenses directory at the root of this repository, also available at
// https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

// Code generated by MockGen. DO NOT EDIT.
// Source: addon_client.go

// Package grpcclient is a generated GoMock package.
package grpcclient

import (
	gomock "github.com/golang/mock/gomock"
	proto "github.com/wings-software/portal/product/ci/addon/proto"
	reflect "reflect"
)

// MockAddonClient is a mock of AddonClient interface.
type MockAddonClient struct {
	ctrl     *gomock.Controller
	recorder *MockAddonClientMockRecorder
}

// MockAddonClientMockRecorder is the mock recorder for MockAddonClient.
type MockAddonClientMockRecorder struct {
	mock *MockAddonClient
}

// NewMockAddonClient creates a new mock instance.
func NewMockAddonClient(ctrl *gomock.Controller) *MockAddonClient {
	mock := &MockAddonClient{ctrl: ctrl}
	mock.recorder = &MockAddonClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAddonClient) EXPECT() *MockAddonClientMockRecorder {
	return m.recorder
}

// CloseConn mocks base method.
func (m *MockAddonClient) CloseConn() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseConn")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseConn indicates an expected call of CloseConn.
func (mr *MockAddonClientMockRecorder) CloseConn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseConn", reflect.TypeOf((*MockAddonClient)(nil).CloseConn))
}

// Client mocks base method.
func (m *MockAddonClient) Client() proto.AddonClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Client")
	ret0, _ := ret[0].(proto.AddonClient)
	return ret0
}

// Client indicates an expected call of Client.
func (mr *MockAddonClientMockRecorder) Client() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Client", reflect.TypeOf((*MockAddonClient)(nil).Client))
}
