package io.harness.pms.events.base;

public enum PmsEventCategory {
  INTERRUPT_EVENT,
  ORCHESTRATION_EVENT,
  FACILITATOR_EVENT,
  NODE_START,
  PROGRESS_EVENT,
  NODE_ADVISE,
  NODE_RESUME,
  CREATE_PARTIAL_PLAN,
  PARTIAL_PLAN_RESPONSE
}
