FROM gcr.io/gke-release/istio/coreos/hyperkube:v1.7.6_coreos.0

RUN apt-get update && apt-get install -y curl jq

#
# mongo
#
RUN curl -O https://repo.mongodb.com/apt/ubuntu/dists/xenial/mongodb-enterprise/4.0/multiverse/binary-amd64/mongodb-enterprise-shell_4.0.4_amd64.deb
RUN dpkg -i mongodb-enterprise-shell_4.0.4_amd64.deb

#
# pip
RUN apt-get install -y gcc python-dev python-setuptools libffi-dev python-pip

#
# gsutil
#
RUN pip install pyasn1 --upgrade
RUN pip install gsutil

CMD ["sh"]
